`timescale 1ns/1ns

module pcb734_220_51 ();
// generated by  HDL Direct 15.70-s009 29-Jul-2008
// on Wed Jan 12 10:57:09 2011
// from pcb734_220_51/PCB734_220_51/sch_1

  wire  \11mhz_clk ;
  wire  \1p2v ;
  wire  \3p3v ;
  wire  \48v_on_cntrl ;
  wire  ad0;
  wire  ad01;
  wire  \ad01_3.3v ;
  wire  ad02;
  wire  \ad02_3.3v ;
  wire  ad03;
  wire  \ad03_3.3v ;
  wire  ad04;
  wire  \ad04_3.3v ;
  wire  ad05;
  wire  \ad05_3.3v ;
  wire  ad06;
  wire  \ad06_3.3v ;
  wire  ad07;
  wire  \ad07_3.3v ;
  wire  ad08;
  wire  \ad08_3.3v ;
  wire  ad09;
  wire  \ad09_3.3v ;
  wire  \ad0_3.3v ;
  wire  ad10;
  wire  \ad10_3.3v ;
  wire  ad11;
  wire  \ad11_3.3v ;
  wire  ad12;
  wire  \ad12_3.3v ;
  wire  ad13;
  wire  \ad13_3.3v ;
  wire  ad14;
  wire  \ad14_3.3v ;
  wire  ad15;
  wire  \ad15_3.3v ;
  wire  \aduc_rd* ;
  wire  \aduc_rd_3.3v* ;
  wire  \aduc_wr* ;
  wire  \aduc_wr_3.3v* ;
  wire  ale;
  wire  \ale_3.3v ;
  wire  ex_lonbus_control;
  wire  ex_lonbus_data;
  wire  gnd0;
  wire  k1_on_cntrl;
  wire  psen;
  wire  \psen_3.3v ;
  wire  \pwrclr* ;
  wire  \pwrclr_3.3v* ;
  wire  sc_lonbus_control;
  wire  sc_lonbus_data;
  wire  sc_p5f;
  wire  \smc_cntrl_bc_48vdc_on* ;
  wire  \smc_cntrl_bc_switched_ac* ;
  wire  \smc_cntrl_bc_switched_ac_3.3v* ;
  wire  \smc_cntrl_dc90_48v_on* ;
  wire  \smc_cntrl_jag_48vdc_on* ;
  wire  \smc_cntrl_jag_switched_ac* ;
  wire  \smc_mon_bc_ac_on* ;
  wire  \smc_mon_bc_ac_on_3.3v* ;
  wire  \smc_mon_bc_ac_pwr_fault* ;
  wire  \smc_mon_bc_ac_pwr_fault_3.3v* ;
  wire  smc_mon_bc_fan0_state;
  wire  \smc_mon_bc_fan0_state_3.3v ;
  wire  smc_mon_bc_fan0_tach_out;
  wire  \smc_mon_bc_fan0_tach_out_3.3v ;
  wire  smc_mon_bc_fan1_state;
  wire  \smc_mon_bc_fan1_state_3.3v ;
  wire  smc_mon_bc_fan1_tach_out;
  wire  \smc_mon_bc_fan1_tach_out_3.3v ;
  wire  \smc_mon_bc_output_fault* ;
  wire  \smc_mon_bc_output_fault_3.3v* ;
  wire  \smc_mon_bc_ovr_tmp* ;
  wire  \smc_mon_bc_ovr_tmp_3.3v* ;
  wire  \smc_mon_bc_phase_loss* ;
  wire  \smc_mon_bc_phase_loss_3.3v* ;
  wire  smc_mon_dc90_48v_on;
  wire  \smc_mon_dc90_48v_on_3.3v ;
  wire  \smc_mon_dc90_ac_pwr_fault* ;
  wire  \smc_mon_dc90_ac_pwr_fault_3.3v* ;
  wire  \smc_mon_dc90_output_fault* ;
  wire  \smc_mon_dc90_output_fault_3.3v* ;
  wire  \smc_mon_dc90_ovr_tmp* ;
  wire  \smc_mon_dc90_ovr_tmp_3.3v* ;
  wire  smc_mon_pdu_jag_48v_good;
  wire  \smc_mon_pdu_jag_48v_good_3.3v ;
  wire  \smc_mon_pdu_jag_thermal_fault* ;
  wire  \smc_mon_pdu_jag_thermal_fault_3.3v* ;
  wire  smc_pdu_48v_on;
  wire  \smc_pdu_48v_on_3.3v ;
  wire  smc_pdu_freq;
  wire  \smc_pdu_freq_3.3v ;
  wire  smc_pdu_i1;
  wire  \smc_pdu_i1_3.3v ;
  wire  smc_pdu_i2;
  wire  \smc_pdu_i2_3.3v ;
  wire  smc_pdu_k1_on;
  wire  \smc_pdu_k1_on_3.3v ;
  wire  smc_pdu_maint;
  wire  \smc_pdu_maint_3.3v ;
  wire  smc_pdu_v0;
  wire  \smc_pdu_v0_3.3v ;
  wire  smc_pdu_v1;
  wire  \smc_pdu_v1_3.3v ;
  wire  smc_pdu_v2;
  wire  \smc_pdu_v2_3.3v ;
  wire  smc_pdu_vab;
  wire  \smc_pdu_vab_3.3v ;
  wire  smc_pdu_vac;
  wire  \smc_pdu_vac_3.3v ;
  wire  smc_pdu_vbc;
  wire  \smc_pdu_vbc_3.3v ;
  wire  smc_sc_fan_in_monitor;
  wire  \smc_sc_fan_in_monitor_3.3v ;
  wire  smc_spr2_fan_in_mon;
  wire  \smc_spr2_fan_in_mon_3.3v ;
  wire  smc_spr_fan_in_monitor;
  wire  \smc_spr_fan_in_monitor_3.3v ;
  wire  smc_th_fan_in_monitor;
  wire  \smc_th_fan_in_monitor_3.3v ;
  wire  tdo;
  wire  th_lonbus_control;
  wire  th_lonbus_data_in;
  wire  th_lonbus_data_out;
  wire  unnamed_4_8res_i102_a;
  wire  unnamed_4_8res_i102_a_1;
  wire  unnamed_4_8res_i102_a_2;
  wire  unnamed_4_8res_i102_a_3;
  wire  unnamed_4_8res_i102_a_4;
  wire  unnamed_4_8res_i102_a_5;
  wire  unnamed_4_8res_i102_a_6;
  wire  unnamed_4_8res_i102_a_7;
  wire  unnamed_4_8res_i103_a;
  wire  unnamed_4_8res_i103_a_1;
  wire  unnamed_4_8res_i103_a_2;
  wire  unnamed_4_8res_i103_a_3;
  wire  unnamed_4_8res_i103_a_4;
  wire  unnamed_4_8res_i103_a_5;
  wire  unnamed_4_8res_i103_a_6;
  wire  unnamed_4_8res_i103_a_7;
  wire  unnamed_4_8res_i104_a;
  wire  unnamed_4_8res_i104_a_1;
  wire  unnamed_4_8res_i104_a_2;
  wire  unnamed_4_8res_i104_a_3;
  wire  unnamed_4_8res_i104_a_4;
  wire  unnamed_4_8res_i104_a_5;
  wire  unnamed_4_8res_i104_a_6;
  wire  unnamed_4_8res_i104_a_7;
  wire  unnamed_4_8res_i105_a;
  wire  unnamed_4_8res_i105_a_1;
  wire  unnamed_4_8res_i105_a_2;
  wire  unnamed_4_8res_i105_a_3;
  wire  unnamed_4_8res_i105_a_4;
  wire  unnamed_4_8res_i105_a_5;
  wire  unnamed_4_8res_i105_a_6;
  wire  unnamed_4_8res_i105_a_7;
  wire  unnamed_4_8res_i106_b;
  wire  unnamed_4_8res_i106_b_1;
  wire  unnamed_4_8res_i106_b_2;
  wire  unnamed_4_8res_i106_b_3;
  wire  unnamed_4_8res_i106_b_4;
  wire  unnamed_4_8res_i106_b_5;
  wire  unnamed_4_8res_i106_b_6;
  wire  unnamed_4_8res_i106_b_7;
  wire  unnamed_4_8res_i268_b;
  wire  unnamed_4_8res_i268_b_1;
  wire  unnamed_4_8res_i268_b_2;
  wire  unnamed_4_8res_i268_b_3;
  wire  unnamed_4_8res_i268_b_4;
  wire  unnamed_4_8res_i268_b_5;
  wire  unnamed_4_8res_i268_b_6;
  wire  unnamed_4_8res_i268_b_7;
  wire  unnamed_4_8res_i269_b;
  wire  unnamed_4_8res_i269_b_1;
  wire  unnamed_4_8res_i269_b_2;
  wire  unnamed_4_8res_i269_b_3;
  wire  unnamed_4_8res_i269_b_4;
  wire  unnamed_4_8res_i269_b_5;
  wire  unnamed_4_8res_i269_b_6;
  wire  unnamed_4_8res_i269_b_7;
  wire  unnamed_4_fct164245tsoic_i100_dir;
  wire  unnamed_4_sres_i226_a;
  wire  unnamed_6_conn10_i365_z;
  wire  unnamed_6_conn10_i368_z;
  wire  unnamed_6_conn10_i369_z;
  wire  unnamed_6_conn10_i373_z;
  wire  unnamed_6_nc7wz17_i24_y;
  wire  unnamed_6_nc7wz17_i260_y;
  wire  unnamed_6_nc7wz17_i260_y_1;
  wire  unnamed_6_nc7wz17_i280_y;
  wire  unnamed_6_nc7wz17_i280_y_1;
  wire  unnamed_6_pres_i223_b;
  wire  unnamed_6_pres_i224_b;
  wire  unnamed_6_pres_i225_a;
  wire  unnamed_6_res_i26_b;
  wire  unnamed_6_smcfpga_i95_spaerfaninput4;
  wire  unnamed_6_smcfpga_i95_sparefaninput3;
  wire  unnamed_6_smcfpga_i97_done;
  wire  unnamed_6_testpoint_i307_tp;

// begin instances 

  fct164245tsoic page4_i96  (.a({unnamed_4_8res_i268_b_5, unnamed_4_8res_i268_b_1, unnamed_4_8res_i268_b_2,
	unnamed_4_8res_i268_b_3, unnamed_4_8res_i268_b_4, unnamed_4_8res_i268_b_7,
	unnamed_4_8res_i268_b_6, unnamed_4_8res_i268_b}),
	.b({smc_pdu_i2, \smc_mon_bc_phase_loss* ,
	\smc_mon_bc_ac_pwr_fault* , smc_mon_pdu_jag_48v_good, smc_pdu_v0, \smc_mon_bc_ovr_tmp* ,
	smc_pdu_i1, \smc_mon_pdu_jag_thermal_fault* }),
	.dir(gnd0),
	.\oe* (gnd0),
	.vdd1_31(/* unconnected */),
	.vdd1_42(/* unconnected */),
	.vdd_7(/* unconnected */),
	.vdd_18(/* unconnected */),
	.vss_4(/* unconnected */),
	.vss_10(/* unconnected */),
	.vss_15(/* unconnected */),
	.vss_21(/* unconnected */),
	.vss_28(/* unconnected */),
	.vss_34(/* unconnected */),
	.vss_39(/* unconnected */),
	.vss_45(/* unconnected */));
  defparam page4_i96.size = 8;

  fct164245tsoic page4_i97  (.a({unnamed_4_8res_i269_b, unnamed_4_8res_i269_b_1, unnamed_4_8res_i269_b_2,
	unnamed_4_8res_i269_b_3, unnamed_4_8res_i269_b_4, unnamed_4_8res_i269_b_5,
	unnamed_4_8res_i269_b_6, unnamed_4_8res_i269_b_7}),
	.b({smc_pdu_k1_on, smc_pdu_vac,
	smc_pdu_vbc, smc_pdu_vab, smc_pdu_48v_on, smc_pdu_v1, smc_pdu_v2, smc_pdu_freq}),
	.dir(gnd0),
	.\oe* (gnd0),
	.vdd1_31(\3p3v ),
	.vdd1_42(\3p3v ),
	.vdd_7(sc_p5f),
	.vdd_18(sc_p5f),
	.vss_4(gnd0),
	.vss_10(gnd0),
	.vss_15(gnd0),
	.vss_21(gnd0),
	.vss_28(gnd0),
	.vss_34(gnd0),
	.vss_39(gnd0),
	.vss_45(gnd0));
  defparam page4_i97.size = 8;

  fct164245tsoic page4_i98  (.a({unnamed_4_8res_i102_a_7, unnamed_4_8res_i102_a_6, unnamed_4_8res_i102_a_5,
	unnamed_4_8res_i102_a_4, unnamed_4_8res_i102_a_3, unnamed_4_8res_i102_a,
	unnamed_4_8res_i102_a_2, unnamed_4_8res_i102_a_1}),
	.b({\smc_mon_bc_output_fault* ,
	\smc_mon_dc90_ovr_tmp* , smc_mon_dc90_48v_on, smc_pdu_maint, \smc_mon_dc90_ac_pwr_fault* ,
	\pwrclr* , \aduc_wr* , \aduc_rd* }),
	.dir(gnd0),
	.\oe* (gnd0),
	.vdd1_31(/* unconnected */),
	.vdd1_42(/* unconnected */),
	.vdd_7(/* unconnected */),
	.vdd_18(/* unconnected */),
	.vss_4(/* unconnected */),
	.vss_10(/* unconnected */),
	.vss_15(/* unconnected */),
	.vss_21(/* unconnected */),
	.vss_28(/* unconnected */),
	.vss_34(/* unconnected */),
	.vss_39(/* unconnected */),
	.vss_45(/* unconnected */));
  defparam page4_i98.size = 8;

  fct164245tsoic page4_i99  (.a({unnamed_4_8res_i103_a_7, unnamed_4_8res_i103_a_6, unnamed_4_8res_i103_a_5,
	unnamed_4_8res_i103_a_4, unnamed_4_8res_i103_a_3, unnamed_4_8res_i103_a_2,
	unnamed_4_8res_i103_a_1, unnamed_4_8res_i103_a}),
	.b({smc_mon_bc_fan1_state, smc_mon_bc_fan0_state,
	smc_mon_bc_fan1_tach_out, smc_mon_bc_fan0_tach_out, ale, psen, \smc_mon_bc_ac_on* ,
	\smc_mon_dc90_output_fault* }),
	.dir(gnd0),
	.\oe* (gnd0),
	.vdd1_31(\3p3v ),
	.vdd1_42(\3p3v ),
	.vdd_7(sc_p5f),
	.vdd_18(sc_p5f),
	.vss_4(gnd0),
	.vss_10(gnd0),
	.vss_15(gnd0),
	.vss_21(gnd0),
	.vss_28(gnd0),
	.vss_34(gnd0),
	.vss_39(gnd0),
	.vss_45(gnd0));
  defparam page4_i99.size = 8;

  fct164245tsoic page4_i100  (.a({unnamed_4_8res_i104_a_6, unnamed_4_8res_i104_a_2, unnamed_4_8res_i104_a_1,
	unnamed_4_8res_i104_a, unnamed_4_8res_i104_a_5, unnamed_4_8res_i104_a_4,
	unnamed_4_8res_i104_a_3, unnamed_4_8res_i104_a_7}),
	.b({unnamed_4_8res_i106_b_2,
	unnamed_4_8res_i106_b_3, unnamed_4_8res_i106_b_1, unnamed_4_8res_i106_b_4,
	unnamed_4_8res_i106_b_6, unnamed_4_8res_i106_b_5, unnamed_4_8res_i106_b,
	unnamed_4_8res_i106_b_7}),
	.dir(unnamed_4_fct164245tsoic_i100_dir),
	.\oe* (gnd0),
	.vdd1_31(/* unconnected */),
	.vdd1_42(/* unconnected */),
	.vdd_7(/* unconnected */),
	.vdd_18(/* unconnected */),
	.vss_4(gnd0),
	.vss_10(gnd0),
	.vss_15(gnd0),
	.vss_21(gnd0),
	.vss_28(gnd0),
	.vss_34(gnd0),
	.vss_39(gnd0),
	.vss_45(gnd0));
  defparam page4_i100.size = 8;

  fct164245tsoic page4_i101  (.a({unnamed_4_8res_i105_a_5, unnamed_4_8res_i105_a_6, unnamed_4_8res_i105_a_2,
	unnamed_4_8res_i105_a, unnamed_4_8res_i105_a_3, unnamed_4_8res_i105_a_1,
	unnamed_4_8res_i105_a_4, unnamed_4_8res_i105_a_7}),
	.b({ad15, ad14, ad13, ad12,
	ad11, ad10, ad09, ad08}),
	.dir(gnd0),
	.\oe* (gnd0),
	.vdd1_31(\3p3v ),
	.vdd1_42(\3p3v ),
	.vdd_7(sc_p5f),
	.vdd_18(sc_p5f),
	.vss_4(gnd0),
	.vss_10(gnd0),
	.vss_15(gnd0),
	.vss_21(gnd0),
	.vss_28(gnd0),
	.vss_34(gnd0),
	.vss_39(gnd0),
	.vss_45(gnd0));
  defparam page4_i101.size = 8;

  \8res  page4_i102  (.a({unnamed_4_8res_i102_a_7, unnamed_4_8res_i102_a_6, unnamed_4_8res_i102_a_5,
	unnamed_4_8res_i102_a_4, unnamed_4_8res_i102_a_3, unnamed_4_8res_i102_a,
	unnamed_4_8res_i102_a_2, unnamed_4_8res_i102_a_1}),
	.b({\smc_mon_bc_output_fault_3.3v* ,
	\smc_mon_dc90_ovr_tmp_3.3v* , \smc_mon_dc90_48v_on_3.3v , \smc_pdu_maint_3.3v ,
	\smc_mon_dc90_ac_pwr_fault_3.3v* , \pwrclr_3.3v* , \aduc_wr_3.3v* , \aduc_rd_3.3v* }));
  defparam page4_i102.size = 8;

  \8res  page4_i103  (.a({unnamed_4_8res_i103_a_7, unnamed_4_8res_i103_a_6, unnamed_4_8res_i103_a_5,
	unnamed_4_8res_i103_a_4, unnamed_4_8res_i103_a_3, unnamed_4_8res_i103_a_2,
	unnamed_4_8res_i103_a_1, unnamed_4_8res_i103_a}),
	.b({\smc_mon_bc_fan1_state_3.3v ,
	\smc_mon_bc_fan0_state_3.3v , \smc_mon_bc_fan1_tach_out_3.3v , \smc_mon_bc_fan0_tach_out_3.3v ,
	\ale_3.3v , \psen_3.3v , \smc_mon_bc_ac_on_3.3v* , \smc_mon_dc90_output_fault_3.3v* }));
  defparam page4_i103.size = 8;

  \8res  page4_i104  (.a({unnamed_4_8res_i104_a_6, unnamed_4_8res_i104_a_2, unnamed_4_8res_i104_a_1,
	unnamed_4_8res_i104_a, unnamed_4_8res_i104_a_5, unnamed_4_8res_i104_a_4,
	unnamed_4_8res_i104_a_3, unnamed_4_8res_i104_a_7}),
	.b({\ad07_3.3v , \ad06_3.3v ,
	\ad05_3.3v , \ad04_3.3v , \ad03_3.3v , \ad02_3.3v , \ad01_3.3v , \ad0_3.3v }));
  defparam page4_i104.size = 8;

  \8res  page4_i105  (.a({unnamed_4_8res_i105_a_5, unnamed_4_8res_i105_a_6, unnamed_4_8res_i105_a_2,
	unnamed_4_8res_i105_a, unnamed_4_8res_i105_a_3, unnamed_4_8res_i105_a_1,
	unnamed_4_8res_i105_a_4, unnamed_4_8res_i105_a_7}),
	.b({\ad15_3.3v , \ad14_3.3v ,
	\ad13_3.3v , \ad12_3.3v , \ad11_3.3v , \ad10_3.3v , \ad09_3.3v , \ad08_3.3v }));
  defparam page4_i105.size = 8;

  \8res  page4_i106  (.a({ad07, ad06, ad05, ad04, ad03, ad02, ad01, ad0}),
	.b({unnamed_4_8res_i106_b_2, unnamed_4_8res_i106_b_3,
	unnamed_4_8res_i106_b_1, unnamed_4_8res_i106_b_4, unnamed_4_8res_i106_b_6,
	unnamed_4_8res_i106_b_5, unnamed_4_8res_i106_b, unnamed_4_8res_i106_b_7}));
  defparam page4_i106.size = 8;

  sres page4_i226  (.a(unnamed_4_sres_i226_a),
	.b(unnamed_4_fct164245tsoic_i100_dir));
  defparam page4_i226.size = 1;

  cap page4_i227  (.a(sc_p5f),
	.b(gnd0));
  defparam page4_i227.size = 1;

  cap page4_i230  (.a(sc_p5f),
	.b(gnd0));
  defparam page4_i230.size = 1;

  cap page4_i231  (.a(\3p3v ),
	.b(gnd0));
  defparam page4_i231.size = 1;

  cap page4_i234  (.a(sc_p5f),
	.b(gnd0));
  defparam page4_i234.size = 1;

  cap page4_i235  (.a(\3p3v ),
	.b(gnd0));
  defparam page4_i235.size = 1;

  cap page4_i236  (.a(sc_p5f),
	.b(gnd0));
  defparam page4_i236.size = 1;

  cap page4_i237  (.a(\3p3v ),
	.b(gnd0));
  defparam page4_i237.size = 1;

  testpoint page4_i244  (.tp(\aduc_rd* ));

  testpoint page4_i245  (.tp(unnamed_4_fct164245tsoic_i100_dir));

  testpoint page4_i246  (.tp(\ad0_3.3v ));

  testpoint page4_i247  (.tp(\ad01_3.3v ));

  testpoint page4_i248  (.tp(\ad02_3.3v ));

  testpoint page4_i249  (.tp(\ad03_3.3v ));

  testpoint page4_i250  (.tp(\smc_mon_bc_ac_on_3.3v* ));

  testpoint page4_i251  (.tp(\psen_3.3v ));

  testpoint page4_i252  (.tp(\aduc_rd_3.3v* ));

  testpoint page4_i253  (.tp(\aduc_wr_3.3v* ));

  testpoint page4_i254  (.tp(\pwrclr_3.3v* ));

  testpoint page4_i255  (.tp(\smc_mon_dc90_ac_pwr_fault_3.3v* ));

  testpoint page4_i256  (.tp(\smc_pdu_maint_3.3v ));

  testpoint page4_i257  (.tp(\smc_mon_dc90_48v_on_3.3v ));

  testpoint page4_i258  (.tp(\smc_pdu_vab_3.3v ));

  testpoint page4_i259  (.tp(\smc_pdu_48v_on_3.3v ));

  testpoint page4_i260  (.tp(\smc_pdu_freq_3.3v ));

  testpoint page4_i261  (.tp(\smc_pdu_k1_on_3.3v ));

  testpoint page4_i262  (.tp(\smc_pdu_i2_3.3v ));

  testpoint page4_i263  (.tp(\smc_mon_bc_phase_loss_3.3v* ));

  testpoint page4_i264  (.tp(\smc_mon_pdu_jag_48v_good_3.3v ));

  testpoint page4_i265  (.tp(\smc_pdu_v0_3.3v ));

  testpoint page4_i266  (.tp(\smc_pdu_i1_3.3v ));

  \8res  page4_i268  (.a({\smc_mon_pdu_jag_thermal_fault_3.3v* , \smc_pdu_i1_3.3v ,
	\smc_mon_bc_ovr_tmp_3.3v* , \smc_pdu_v0_3.3v , \smc_mon_pdu_jag_48v_good_3.3v ,
	\smc_mon_bc_ac_pwr_fault_3.3v* , \smc_mon_bc_phase_loss_3.3v* , \smc_pdu_i2_3.3v }),
	.b({unnamed_4_8res_i268_b, unnamed_4_8res_i268_b_6, unnamed_4_8res_i268_b_7,
	unnamed_4_8res_i268_b_4, unnamed_4_8res_i268_b_3, unnamed_4_8res_i268_b_2,
	unnamed_4_8res_i268_b_1, unnamed_4_8res_i268_b_5}));
  defparam page4_i268.size = 8;

  \8res  page4_i269  (.a({\smc_pdu_freq_3.3v , \smc_pdu_v2_3.3v ,
	\smc_pdu_v1_3.3v , \smc_pdu_48v_on_3.3v , \smc_pdu_vab_3.3v , \smc_pdu_vbc_3.3v ,
	\smc_pdu_vac_3.3v , \smc_pdu_k1_on_3.3v }),
	.b({unnamed_4_8res_i269_b_7, unnamed_4_8res_i269_b_6,
	unnamed_4_8res_i269_b_5, unnamed_4_8res_i269_b_4, unnamed_4_8res_i269_b_3,
	unnamed_4_8res_i269_b_2, unnamed_4_8res_i269_b_1, unnamed_4_8res_i269_b}));
  defparam page4_i269.size = 8;

  tc7szu04f page4_i270  (.a(\aduc_rd* ),
	.vdd1(sc_p5f),
	.vss(gnd0),
	.\y* (unnamed_4_sres_i226_a));

  nc7wz17 page6_i24  (.a({\11mhz_clk , gnd0}),
	.gnd(gnd0),
	.vcc(\3p3v ),
	.y({unnamed_6_nc7wz17_i24_y, open_p1$1}));
  defparam page6_i24.size = 2;

  cap page6_i25  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i25.size = 1;

  res page6_i26  (.a(unnamed_6_nc7wz17_i24_y),
	.b(unnamed_6_res_i26_b));
  defparam page6_i26.size = 1;

  smc_fpga page6_i94  (.\48v_on_cntl (\48v_on_cntrl ),
	.ad0(\ad0_3.3v ),
	.ad01(\ad01_3.3v ),
	.ad02(\ad02_3.3v ),
	.ad03(\ad03_3.3v ),
	.ad04(\ad04_3.3v ),
	.ad05(\ad05_3.3v ),
	.ad06(\ad06_3.3v ),
	.ad07(\ad07_3.3v ),
	.ad08(\ad08_3.3v ),
	.ad09(\ad09_3.3v ),
	.ad10(\ad10_3.3v ),
	.ad11(\ad11_3.3v ),
	.ad12(\ad12_3.3v ),
	.ad13(\ad13_3.3v ),
	.ad14(\ad14_3.3v ),
	.ad15(\ad15_3.3v ),
	.\aduc_rd* (\aduc_rd_3.3v* ),
	.\aduc_wr* (\aduc_wr_3.3v* ),
	.\cntl_bc_48vdc_on* (\smc_cntrl_bc_48vdc_on* ),
	.\cntl_bc_switched_ac* (\smc_cntrl_bc_switched_ac_3.3v* ),
	.\cntl_jag_48vdc_on* (\smc_cntrl_jag_48vdc_on* ),
	.\cntl_jag_switched_ac* (\smc_cntrl_jag_switched_ac* ),
	.k1_on_cntl(k1_on_cntrl),
	.led_cathode(/* unconnected */),
	.\pdu_48v_on/jaj_48v_on (\smc_pdu_48v_on_3.3v ),
	.\pdu_k1_on/jag_k1_on (\smc_pdu_k1_on_3.3v ),
	.psen(\psen_3.3v ),
	.\pwrclr* (\pwrclr_3.3v* ),
	.\smc_en_tsp_on* (/* unconnected */),
	.\smc_ready* (/* unconnected */),
	.\tsp_off* (/* unconnected */),
	.\tsp_on* (/* unconnected */),
	.\tsp_on_request* (/* unconnected */),
	.\cntl_dc90_48v_on* (/* unconnected */),
	.done(/* unconnected */),
	.ex_lonbus_cntl(/* unconnected */),
	.sc_lonbus_cntl(/* unconnected */),
	.tdo(/* unconnected */),
	.th_lonbus_cntl(/* unconnected */),
	.th_lonbus_data_out(/* unconnected */),
	.ex_lonbus_data(/* unconnected */),
	.sc_lonbus_data(/* unconnected */),
	.\bc_ac_on* (/* unconnected */),
	.\bc_ac_pwr_fault* (/* unconnected */),
	.bc_fan0_state(/* unconnected */),
	.bc_fan0_tach(/* unconnected */),
	.bc_fan1_state(/* unconnected */),
	.bc_fan1_tach(/* unconnected */),
	.\bc_output_fault* (/* unconnected */),
	.\bc_ovr_tmp* (/* unconnected */),
	.\bc_phase_loss* (/* unconnected */),
	.dc90_48v_on(/* unconnected */),
	.\dc90_ac_pwr_fault* (/* unconnected */),
	.\dc90_output_fault* (/* unconnected */),
	.\dc90_ovr_tmp* (/* unconnected */),
	.gnd(/* unconnected */),
	.\io/gclk8 (/* unconnected */),
	.\io/gclk14 (/* unconnected */),
	.m0(/* unconnected */),
	.m1(/* unconnected */),
	.m2(/* unconnected */),
	.pdu_freq(/* unconnected */),
	.pdu_i1(/* unconnected */),
	.pdu_i2(/* unconnected */),
	.pdu_jag_48v_good(/* unconnected */),
	.\pdu_jag_thermal_fault* (/* unconnected */),
	.pdu_maint(/* unconnected */),
	.pdu_v0(/* unconnected */),
	.pdu_v1(/* unconnected */),
	.pdu_v2(/* unconnected */),
	.pdu_vab(/* unconnected */),
	.pdu_vac(/* unconnected */),
	.pdu_vbc(/* unconnected */),
	.\prog_b* (/* unconnected */),
	.spaer_fan_input_1(/* unconnected */),
	.spaer_fan_input_4(/* unconnected */),
	.spare_fan_input_2(/* unconnected */),
	.spare_fan_input_3(/* unconnected */),
	.support_cabinet_fan(/* unconnected */),
	.suspend(/* unconnected */),
	.tck(/* unconnected */),
	.tdi(/* unconnected */),
	.th_blower(/* unconnected */),
	.th_lonbus_data_in(/* unconnected */),
	.tms(/* unconnected */),
	.vccaux(/* unconnected */),
	.vccint(/* unconnected */),
	.vcco_0(/* unconnected */),
	.vcco_1(/* unconnected */),
	.vcco_2(/* unconnected */),
	.vcco_3(/* unconnected */));

  smc_fpga page6_i95  (.\bc_ac_on* (\smc_mon_bc_ac_on_3.3v* ),
	.\bc_ac_pwr_fault* (\smc_mon_bc_ac_pwr_fault_3.3v* ),
	.bc_fan0_state(\smc_mon_bc_fan0_state_3.3v ),
	.bc_fan0_tach(\smc_mon_bc_fan0_tach_out_3.3v ),
	.bc_fan1_state(\smc_mon_bc_fan1_state_3.3v ),
	.bc_fan1_tach(\smc_mon_bc_fan1_tach_out_3.3v ),
	.\bc_output_fault* (\smc_mon_dc90_output_fault_3.3v* ),
	.\bc_ovr_tmp* (\smc_mon_bc_ovr_tmp_3.3v* ),
	.\bc_phase_loss* (\smc_mon_bc_phase_loss_3.3v* ),
	.\cntl_dc90_48v_on* (\smc_cntrl_dc90_48v_on* ),
	.dc90_48v_on(\smc_mon_dc90_48v_on_3.3v ),
	.\dc90_ac_pwr_fault* (\smc_mon_dc90_ac_pwr_fault_3.3v* ),
	.\dc90_output_fault* (\smc_mon_bc_output_fault_3.3v* ),
	.\dc90_ovr_tmp* (\smc_mon_dc90_ovr_tmp_3.3v* ),
	.ex_lonbus_cntl(ex_lonbus_control),
	.ex_lonbus_data(ex_lonbus_data),
	.pdu_freq(\smc_pdu_freq_3.3v ),
	.pdu_i1(\smc_pdu_i1_3.3v ),
	.pdu_i2(\smc_pdu_i2_3.3v ),
	.pdu_jag_48v_good(\smc_mon_pdu_jag_48v_good_3.3v ),
	.\pdu_jag_thermal_fault* (\smc_mon_pdu_jag_thermal_fault_3.3v* ),
	.pdu_maint(\smc_pdu_maint_3.3v ),
	.pdu_v0(\smc_pdu_v0_3.3v ),
	.pdu_v1(\smc_pdu_v1_3.3v ),
	.pdu_v2(\smc_pdu_v2_3.3v ),
	.pdu_vab(\smc_pdu_vab_3.3v ),
	.pdu_vac(\smc_pdu_vac_3.3v ),
	.pdu_vbc(\smc_pdu_vbc_3.3v ),
	.sc_lonbus_cntl(sc_lonbus_control),
	.sc_lonbus_data(sc_lonbus_data),
	.spaer_fan_input_1(\smc_spr_fan_in_monitor_3.3v ),
	.spaer_fan_input_4(unnamed_6_smcfpga_i95_spaerfaninput4),
	.spare_fan_input_2(\smc_spr2_fan_in_mon_3.3v ),
	.spare_fan_input_3(unnamed_6_smcfpga_i95_sparefaninput3),
	.support_cabinet_fan(\smc_sc_fan_in_monitor_3.3v ),
	.th_blower(\smc_th_fan_in_monitor_3.3v ),
	.th_lonbus_cntl(th_lonbus_control),
	.th_lonbus_data_in(th_lonbus_data_in),
	.th_lonbus_data_out(th_lonbus_data_out),
	.\48v_on_cntl (/* unconnected */),
	.\cntl_bc_48vdc_on* (/* unconnected */),
	.\cntl_bc_switched_ac* (/* unconnected */),
	.\cntl_jag_48vdc_on* (/* unconnected */),
	.\cntl_jag_switched_ac* (/* unconnected */),
	.done(/* unconnected */),
	.k1_on_cntl(/* unconnected */),
	.led_cathode(/* unconnected */),
	.tdo(/* unconnected */),
	.\tsp_on_request* (/* unconnected */),
	.ad0(/* unconnected */),
	.ad01(/* unconnected */),
	.ad02(/* unconnected */),
	.ad03(/* unconnected */),
	.ad04(/* unconnected */),
	.ad05(/* unconnected */),
	.ad06(/* unconnected */),
	.ad07(/* unconnected */),
	.ad08(/* unconnected */),
	.ad09(/* unconnected */),
	.ad10(/* unconnected */),
	.ad11(/* unconnected */),
	.ad12(/* unconnected */),
	.ad13(/* unconnected */),
	.ad14(/* unconnected */),
	.ad15(/* unconnected */),
	.\aduc_rd* (/* unconnected */),
	.\aduc_wr* (/* unconnected */),
	.gnd(/* unconnected */),
	.\io/gclk8 (/* unconnected */),
	.\io/gclk14 (/* unconnected */),
	.m0(/* unconnected */),
	.m1(/* unconnected */),
	.m2(/* unconnected */),
	.\pdu_48v_on/jaj_48v_on (/* unconnected */),
	.\pdu_k1_on/jag_k1_on (/* unconnected */),
	.\prog_b* (/* unconnected */),
	.psen(/* unconnected */),
	.\pwrclr* (/* unconnected */),
	.\smc_en_tsp_on* (/* unconnected */),
	.\smc_ready* (/* unconnected */),
	.suspend(/* unconnected */),
	.tck(/* unconnected */),
	.tdi(/* unconnected */),
	.tms(/* unconnected */),
	.\tsp_off* (/* unconnected */),
	.\tsp_on* (/* unconnected */),
	.vccaux(/* unconnected */),
	.vccint(/* unconnected */),
	.vcco_0(/* unconnected */),
	.vcco_1(/* unconnected */),
	.vcco_2(/* unconnected */),
	.vcco_3(/* unconnected */));

  smc_fpga page6_i96  (.gnd({gnd0, gnd0, gnd0, gnd0, gnd0, gnd0, gnd0, gnd0, gnd0, gnd0,
	gnd0, gnd0, gnd0}),
	.vccaux({\3p3v , \3p3v , \3p3v , \3p3v }),
	.vccint({\1p2v , \1p2v , \1p2v ,
	\1p2v }),
	.vcco_0({\3p3v , \3p3v }),
	.vcco_1({\3p3v , \3p3v }),
	.vcco_2({\3p3v , \3p3v }),
	.vcco_3({\3p3v , \3p3v }),
	.\48v_on_cntl (/* unconnected */),
	.\cntl_bc_48vdc_on* (/* unconnected */),
	.\cntl_bc_switched_ac* (/* unconnected */),
	.\cntl_dc90_48v_on* (/* unconnected */),
	.\cntl_jag_48vdc_on* (/* unconnected */),
	.\cntl_jag_switched_ac* (/* unconnected */),
	.done(/* unconnected */),
	.ex_lonbus_cntl(/* unconnected */),
	.k1_on_cntl(/* unconnected */),
	.led_cathode(/* unconnected */),
	.sc_lonbus_cntl(/* unconnected */),
	.tdo(/* unconnected */),
	.th_lonbus_cntl(/* unconnected */),
	.th_lonbus_data_out(/* unconnected */),
	.\tsp_on_request* (/* unconnected */),
	.ad0(/* unconnected */),
	.ad01(/* unconnected */),
	.ad02(/* unconnected */),
	.ad03(/* unconnected */),
	.ad04(/* unconnected */),
	.ad05(/* unconnected */),
	.ad06(/* unconnected */),
	.ad07(/* unconnected */),
	.ex_lonbus_data(/* unconnected */),
	.sc_lonbus_data(/* unconnected */),
	.ad08(/* unconnected */),
	.ad09(/* unconnected */),
	.ad10(/* unconnected */),
	.ad11(/* unconnected */),
	.ad12(/* unconnected */),
	.ad13(/* unconnected */),
	.ad14(/* unconnected */),
	.ad15(/* unconnected */),
	.\aduc_rd* (/* unconnected */),
	.\aduc_wr* (/* unconnected */),
	.\bc_ac_on* (/* unconnected */),
	.\bc_ac_pwr_fault* (/* unconnected */),
	.bc_fan0_state(/* unconnected */),
	.bc_fan0_tach(/* unconnected */),
	.bc_fan1_state(/* unconnected */),
	.bc_fan1_tach(/* unconnected */),
	.\bc_output_fault* (/* unconnected */),
	.\bc_ovr_tmp* (/* unconnected */),
	.\bc_phase_loss* (/* unconnected */),
	.dc90_48v_on(/* unconnected */),
	.\dc90_ac_pwr_fault* (/* unconnected */),
	.\dc90_output_fault* (/* unconnected */),
	.\dc90_ovr_tmp* (/* unconnected */),
	.\io/gclk8 (/* unconnected */),
	.\io/gclk14 (/* unconnected */),
	.m0(/* unconnected */),
	.m1(/* unconnected */),
	.m2(/* unconnected */),
	.\pdu_48v_on/jaj_48v_on (/* unconnected */),
	.pdu_freq(/* unconnected */),
	.pdu_i1(/* unconnected */),
	.pdu_i2(/* unconnected */),
	.pdu_jag_48v_good(/* unconnected */),
	.\pdu_jag_thermal_fault* (/* unconnected */),
	.\pdu_k1_on/jag_k1_on (/* unconnected */),
	.pdu_maint(/* unconnected */),
	.pdu_v0(/* unconnected */),
	.pdu_v1(/* unconnected */),
	.pdu_v2(/* unconnected */),
	.pdu_vab(/* unconnected */),
	.pdu_vac(/* unconnected */),
	.pdu_vbc(/* unconnected */),
	.\prog_b* (/* unconnected */),
	.psen(/* unconnected */),
	.\pwrclr* (/* unconnected */),
	.\smc_en_tsp_on* (/* unconnected */),
	.\smc_ready* (/* unconnected */),
	.spaer_fan_input_1(/* unconnected */),
	.spaer_fan_input_4(/* unconnected */),
	.spare_fan_input_2(/* unconnected */),
	.spare_fan_input_3(/* unconnected */),
	.support_cabinet_fan(/* unconnected */),
	.suspend(/* unconnected */),
	.tck(/* unconnected */),
	.tdi(/* unconnected */),
	.th_blower(/* unconnected */),
	.th_lonbus_data_in(/* unconnected */),
	.tms(/* unconnected */),
	.\tsp_off* (/* unconnected */),
	.\tsp_on* (/* unconnected */));

  smc_fpga page6_i97  (.done(unnamed_6_smcfpga_i97_done),
	.\io/gclk8 (\ale_3.3v ),
	.\io/gclk14 (unnamed_6_res_i26_b),
	.m0(unnamed_6_pres_i224_b),
	.m1(unnamed_6_pres_i223_b),
	.m2(unnamed_6_pres_i225_a),
	.\prog_b* (/* unconnected */),
	.suspend(gnd0),
	.tck(unnamed_6_conn10_i365_z),
	.tdi(unnamed_6_conn10_i373_z),
	.tdo(tdo),
	.tms(unnamed_6_conn10_i369_z),
	.\48v_on_cntl (/* unconnected */),
	.\cntl_bc_48vdc_on* (/* unconnected */),
	.\cntl_bc_switched_ac* (/* unconnected */),
	.\cntl_dc90_48v_on* (/* unconnected */),
	.\cntl_jag_48vdc_on* (/* unconnected */),
	.\cntl_jag_switched_ac* (/* unconnected */),
	.ex_lonbus_cntl(/* unconnected */),
	.k1_on_cntl(/* unconnected */),
	.led_cathode(/* unconnected */),
	.sc_lonbus_cntl(/* unconnected */),
	.th_lonbus_cntl(/* unconnected */),
	.th_lonbus_data_out(/* unconnected */),
	.\tsp_on_request* (/* unconnected */),
	.ad0(/* unconnected */),
	.ad01(/* unconnected */),
	.ad02(/* unconnected */),
	.ad03(/* unconnected */),
	.ad04(/* unconnected */),
	.ad05(/* unconnected */),
	.ad06(/* unconnected */),
	.ad07(/* unconnected */),
	.ex_lonbus_data(/* unconnected */),
	.sc_lonbus_data(/* unconnected */),
	.ad08(/* unconnected */),
	.ad09(/* unconnected */),
	.ad10(/* unconnected */),
	.ad11(/* unconnected */),
	.ad12(/* unconnected */),
	.ad13(/* unconnected */),
	.ad14(/* unconnected */),
	.ad15(/* unconnected */),
	.\aduc_rd* (/* unconnected */),
	.\aduc_wr* (/* unconnected */),
	.\bc_ac_on* (/* unconnected */),
	.\bc_ac_pwr_fault* (/* unconnected */),
	.bc_fan0_state(/* unconnected */),
	.bc_fan0_tach(/* unconnected */),
	.bc_fan1_state(/* unconnected */),
	.bc_fan1_tach(/* unconnected */),
	.\bc_output_fault* (/* unconnected */),
	.\bc_ovr_tmp* (/* unconnected */),
	.\bc_phase_loss* (/* unconnected */),
	.dc90_48v_on(/* unconnected */),
	.\dc90_ac_pwr_fault* (/* unconnected */),
	.\dc90_output_fault* (/* unconnected */),
	.\dc90_ovr_tmp* (/* unconnected */),
	.gnd(/* unconnected */),
	.\pdu_48v_on/jaj_48v_on (/* unconnected */),
	.pdu_freq(/* unconnected */),
	.pdu_i1(/* unconnected */),
	.pdu_i2(/* unconnected */),
	.pdu_jag_48v_good(/* unconnected */),
	.\pdu_jag_thermal_fault* (/* unconnected */),
	.\pdu_k1_on/jag_k1_on (/* unconnected */),
	.pdu_maint(/* unconnected */),
	.pdu_v0(/* unconnected */),
	.pdu_v1(/* unconnected */),
	.pdu_v2(/* unconnected */),
	.pdu_vab(/* unconnected */),
	.pdu_vac(/* unconnected */),
	.pdu_vbc(/* unconnected */),
	.psen(/* unconnected */),
	.\pwrclr* (/* unconnected */),
	.\smc_en_tsp_on* (/* unconnected */),
	.\smc_ready* (/* unconnected */),
	.spaer_fan_input_1(/* unconnected */),
	.spaer_fan_input_4(/* unconnected */),
	.spare_fan_input_2(/* unconnected */),
	.spare_fan_input_3(/* unconnected */),
	.support_cabinet_fan(/* unconnected */),
	.th_blower(/* unconnected */),
	.th_lonbus_data_in(/* unconnected */),
	.\tsp_off* (/* unconnected */),
	.\tsp_on* (/* unconnected */),
	.vccaux(/* unconnected */),
	.vccint(/* unconnected */),
	.vcco_0(/* unconnected */),
	.vcco_1(/* unconnected */),
	.vcco_2(/* unconnected */),
	.vcco_3(/* unconnected */));

  lp3891esx page6_i211  (.bias(sc_p5f),
	.gndtab(gnd0),
	.gnd_3(gnd0),
	.\input (\3p3v ),
	.\output (\1p2v ),
	.\shdn* (sc_p5f));

  pres page6_i223  (.a(\3p3v ),
	.b(unnamed_6_pres_i223_b));
  defparam page6_i223.size = 1;

  pres page6_i224  (.a(\3p3v ),
	.b(unnamed_6_pres_i224_b));
  defparam page6_i224.size = 1;

  pres page6_i225  (.a(unnamed_6_pres_i225_a),
	.b(gnd0));
  defparam page6_i225.size = 1;

  cap page6_i243  (.a(sc_p5f),
	.b(gnd0));
  defparam page6_i243.size = 1;

  testpoint page6_i251  (.tp(unnamed_6_conn10_i369_z));

  testpoint page6_i255  (.tp(tdo));

  polcap page6_i256  (.neg(gnd0),
	.pos(\3p3v ));
  defparam page6_i256.size = 1;

  polcap page6_i257  (.neg(gnd0),
	.pos(\1p2v ));
  defparam page6_i257.size = 1;

  nc7wz17 page6_i260  (.a({smc_spr2_fan_in_mon, smc_spr_fan_in_monitor}),
	.gnd(gnd0),
	.vcc(\3p3v ),
	.y({unnamed_6_nc7wz17_i260_y_1, unnamed_6_nc7wz17_i260_y}));
  defparam page6_i260.size = 2;

  res page6_i261  (.a(unnamed_6_nc7wz17_i260_y),
	.b(\smc_spr_fan_in_monitor_3.3v ));
  defparam page6_i261.size = 1;

  res page6_i262  (.a(unnamed_6_nc7wz17_i260_y_1),
	.b(\smc_spr2_fan_in_mon_3.3v ));
  defparam page6_i262.size = 1;

  res page6_i263  (.a(smc_spr_fan_in_monitor),
	.b(\smc_spr_fan_in_monitor_3.3v ));
  defparam page6_i263.size = 1;

  res page6_i264  (.a(smc_spr2_fan_in_mon),
	.b(\smc_spr2_fan_in_mon_3.3v ));
  defparam page6_i264.size = 1;

  res page6_i270  (.a(smc_th_fan_in_monitor),
	.b(\smc_th_fan_in_monitor_3.3v ));
  defparam page6_i270.size = 1;

  res page6_i273  (.a(unnamed_6_nc7wz17_i280_y),
	.b(\smc_th_fan_in_monitor_3.3v ));
  defparam page6_i273.size = 1;

  res page6_i274  (.a(unnamed_6_nc7wz17_i280_y_1),
	.b(\smc_sc_fan_in_monitor_3.3v ));
  defparam page6_i274.size = 1;

  res page6_i275  (.a(smc_sc_fan_in_monitor),
	.b(\smc_sc_fan_in_monitor_3.3v ));
  defparam page6_i275.size = 1;

  nc7wz17 page6_i280  (.a({smc_sc_fan_in_monitor, smc_th_fan_in_monitor}),
	.gnd(gnd0),
	.vcc(\3p3v ),
	.y({unnamed_6_nc7wz17_i280_y_1, unnamed_6_nc7wz17_i280_y}));
  defparam page6_i280.size = 2;

  cap page6_i281  (.a(gnd0),
	.b(\3p3v ));
  defparam page6_i281.size = 1;

  cap page6_i282  (.a(gnd0),
	.b(\3p3v ));
  defparam page6_i282.size = 1;

  testpoint page6_i283  (.tp(\smc_spr_fan_in_monitor_3.3v ));

  testpoint page6_i284  (.tp(\smc_spr2_fan_in_mon_3.3v ));

  testpoint page6_i285  (.tp(\smc_th_fan_in_monitor_3.3v ));

  testpoint page6_i286  (.tp(\smc_sc_fan_in_monitor_3.3v ));

  res page6_i287  (.a(\smc_spr2_fan_in_mon_3.3v ),
	.b(unnamed_6_smcfpga_i95_spaerfaninput4));
  defparam page6_i287.size = 1;

  res page6_i288  (.a(\smc_spr_fan_in_monitor_3.3v ),
	.b(unnamed_6_smcfpga_i95_sparefaninput3));
  defparam page6_i288.size = 1;

  res page6_i290  (.a(unnamed_6_conn10_i368_z),
	.b(\3p3v ));
  defparam page6_i290.size = 1;

  testpoint page6_i291  (.tp(unnamed_6_conn10_i373_z));

  testpoint page6_i292  (.tp(sc_lonbus_data));

  testpoint page6_i293  (.tp(ex_lonbus_data));

  testpoint page6_i294  (.tp(th_lonbus_data_in));

  testpoint page6_i295  (.tp(sc_lonbus_control));

  testpoint page6_i296  (.tp(ex_lonbus_control));

  testpoint page6_i297  (.tp(th_lonbus_data_out));

  testpoint page6_i298  (.tp(th_lonbus_control));

  testpoint page6_i299  (.tp(\48v_on_cntrl ));

  testpoint page6_i300  (.tp(\smc_cntrl_bc_48vdc_on* ));

  testpoint page6_i301  (.tp(\smc_cntrl_jag_48vdc_on* ));

  testpoint page6_i302  (.tp(k1_on_cntrl));

  testpoint page6_i304  (.tp(\smc_cntrl_jag_switched_ac* ));

  testpoint page6_i305  (.tp(\smc_cntrl_dc90_48v_on* ));

  testpoint page6_i307  (.tp(unnamed_6_testpoint_i307_tp));

  bsp123_e6327 page6_i341  (.d(\smc_cntrl_bc_switched_ac* ),
	.d2(\smc_cntrl_bc_switched_ac* ),
	.g(\smc_cntrl_bc_switched_ac_3.3v* ),
	.s(gnd0));

  testpoint page6_i342  (.tp(\smc_cntrl_bc_switched_ac* ));

  sres page6_i344  (.a(sc_p5f),
	.b(\smc_cntrl_bc_switched_ac* ));
  defparam page6_i344.size = 1;

  cap page6_i347  (.a(\1p2v ),
	.b(gnd0));
  defparam page6_i347.size = 1;

  cap page6_i348  (.a(\1p2v ),
	.b(gnd0));
  defparam page6_i348.size = 1;

  cap page6_i349  (.a(\1p2v ),
	.b(gnd0));
  defparam page6_i349.size = 1;

  cap page6_i350  (.a(\1p2v ),
	.b(gnd0));
  defparam page6_i350.size = 1;

  cap page6_i351  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i351.size = 1;

  cap page6_i352  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i352.size = 1;

  cap page6_i353  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i353.size = 1;

  cap page6_i354  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i354.size = 1;

  cap page6_i355  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i355.size = 1;

  cap page6_i356  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i356.size = 1;

  cap page6_i357  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i357.size = 1;

  cap page6_i358  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i358.size = 1;

  cap page6_i359  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i359.size = 1;

  cap page6_i360  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i360.size = 1;

  cap page6_i361  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i361.size = 1;

  cap page6_i362  (.a(\3p3v ),
	.b(gnd0));
  defparam page6_i362.size = 1;

  conn10 page6_i365  (.z(unnamed_6_conn10_i365_z));

  conn10 page6_i366  (.z(gnd0));

  conn10 page6_i367  (.z(tdo));

  conn10 page6_i368  (.z(unnamed_6_conn10_i368_z));

  conn10 page6_i369  (.z(unnamed_6_conn10_i369_z));

  conn10 page6_i370  (.z(unnamed_6_conn10_i368_z));

  conn10 page6_i371  (.z(/* unconnected */));

  conn10 page6_i372  (.z(/* unconnected */));

  conn10 page6_i373  (.z(unnamed_6_conn10_i373_z));

  conn10 page6_i374  (.z(gnd0));

endmodule // pcb734_220_51(sch_1) 
