/*
****************************************************************************

   IMAGE HEADER FILE FOR INSTRUMENT SMC_FPGA

   PREPARED BY IDL VERSION 2.30e 

   DO NOT EDIT THIS FILE - YOU'LL LOOSE THE ABILITY TO RERUN IDL 

Assumes the availability of the routine:                    
 tl_idl_init()     - to initialze the reg. buffer          
 tl_idl_set_base() - to set the base board address         
 tl_idl_w()        - to write a register                   
 tl_idl_r()        - to read a register                    
 tl_idl_dump()     - debug dump of all regs                

****************************************************************************
*/

#ident "%W% %G% Copyright Teradyne, Inc. "

#ifndef smc_fpga_idl_h
#define smc_fpga_idl_h    1

/****ADDRESS SPACE NOT REPLICATED****/
#define SMC_FPGA_BASE 0x0

extern IdlOneBoard * tl_smc_fpga_regs;        
extern IdlOneBoard * tl_smc_fpga_shadow_reg();
extern IdlOneBoard * tl_idl_init();     

extern void tl_tcio_32w();
extern unsigned int  tl_tcio_32r();

/****************************************************************************
   List of all registers for Instrument SMC_FPGA
****************************************************************************/
enum SMC_FPGA_REGS {
   SMC_FPGA_V48_ON,               /* width 1 */
   SMC_FPGA_V48_ENABLE,           /* width 1 */
   SMC_FPGA_K1_ON,                /* width 1 */
   SMC_FPGA_K1_ENABLE,            /* width 1 */
   SMC_FPGA_AUX_FAN_CTL,          /* width 2 */
   SMC_FPGA_AUX_0_CTL,            /* width 2 */
   SMC_FPGA_AUX_1_CTL,            /* width 2 */
   SMC_FPGA_AUX_2_CTL,            /* width 2 */
   SMC_FPGA_AUX_3_CTL,            /* width 2 */
   SMC_FPGA_RESET,                /* width 4 */
   SMC_FPGA_CTR_CTL,              /* width 1 */
   SMC_FPGA_GEN_FREQ_CTR_MUX,     /* width 5 */
   SMC_FPGA_V0_LO,                /* width 8 */
   SMC_FPGA_V0_HI,                /* width 8 */
   SMC_FPGA_I1_LO,                /* width 8 */
   SMC_FPGA_I1_HI,                /* width 8 */
   SMC_FPGA_I2_LO,                /* width 8 */
   SMC_FPGA_I2_HI,                /* width 8 */
   SMC_FPGA_MAIN_BLOWER_LO,       /* width 8 */
   SMC_FPGA_MAIN_BLOWER_HI,       /* width 8 */
   SMC_FPGA_GEN_FREQ_CTR_LO,      /* width 8 */
   SMC_FPGA_GEN_FREQ_CTR_MID,     /* width 8 */
   SMC_FPGA_GEN_FREQ_CTR_HI,      /* width 8 */
   SMC_FPGA_BC_TACH0_CTR_LO,      /* width 8 */
   SMC_FPGA_BC_TACH0_CTR_HI,      /* width 8 */
   SMC_FPGA_BC_TACH1_CTR_LO,      /* width 8 */
   SMC_FPGA_BC_TACH1_CTR_HI,      /* width 8 */
   SMC_FPGA_BC_TACH_CTL,          /* width 2 */
   SMC_FPGA_ID_REV,               /* width 8 */
   SMC_FPGA_MAINT_MON,            /* width 2 */
   SMC_FPGA_LOCK_OUT_STATE,       /* width 7 */
   SMC_FPGA_B_CNTRL_BC_48VDC,     /* width 1 */
   SMC_FPGA_B_DC90_48V_Enable,    /* width 1 */
   SMC_FPGA_B_CNTRL_BC_48VDC_DC90, /* width 1 */
   SMC_FPGA_DC90_STATE,           /* width 4 */
   SMC_FPGA_STATE_48V,            /* width 4 */
   SMC_FPGA_STATE_BC_FAN,         /* width 2 */
   SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC, /* width 1 */
   SMC_FPGA_SMC_MON_BC_AC_ON,     /* width 1 */
   SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC, /* width 1 */
   SMC_FPGA_SMC_MON_PDU_K1,       /* width 1 */
   SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON, /* width 1 */
   SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD, /* width 1 */
   SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON, /* width 1 */
   SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT, /* width 1 */
   MAX_SMC_FPGA_REGS,            
   };


/****************************************************************************
   Field SMC_MON_PDU_JAG_THERMAL_FAULT                                     
    Thermal Fault output from 48V Jag Power Supply                           
****************************************************************************/
#define SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT__MASK 0x1     
#define SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT__ADDR 0xb30a  


/****************************************************************************
   Field SMC_MON_PDU_JAG_48V_LVL_ON                                        
     Used on Jaguar this is feedback for the control Input Signal, On=Low    
****************************************************************************/
#define SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON__MASK 0x1     
#define SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON__ADDR 0xb32c  


/****************************************************************************
   Field SMC_MON_PDU_JAG_48V_GOOD                                          
    BOBCAT 48V interlock OK = Low, Jag output OK OK = HIGH                   
****************************************************************************/
#define SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD__MASK 0x1     
#define SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD__ADDR 0xb311  


/****************************************************************************
   Field SMC_CNTRL_JAG_48VDC_ON                                            
    On/off control bit for Jaguar 48V                                        
****************************************************************************/
#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON__MASK 0x1     
#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON__SHIFT 0x0     
#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON__ADDR 0xb306  
#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_ON 0x1     
#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_OFF 0x0     


/****************************************************************************
   Field SMC_MON_PDU_K1                                                    
    On/off control readback bit for K1                                       
****************************************************************************/
#define SMC_FPGA_SMC_MON_PDU_K1__MASK  0x1     
#define SMC_FPGA_SMC_MON_PDU_K1__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_PDU_K1__ADDR  0xb303  
#define SMC_FPGA_SMC_MON_PDU_K1_CLR    0x0     


/****************************************************************************
   Field SMC_CNTRL_JAG_SWITCHED_AC                                         
    On/off control bit for Jaguar AC                                         
****************************************************************************/
#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC__MASK 0x1     
#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC__SHIFT 0x0     
#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC__ADDR 0xb302  
#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_ON 0x1     
#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_OFF 0x0     


/****************************************************************************
   Field SMC_MON_BC_AC_ON                                                  
    On/off control readback bit for K1                                       
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_AC_ON__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_AC_ON__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_BC_AC_ON__ADDR 0xb32a  


/****************************************************************************
   Field B_SMC_CNTRL_BC_SWITCHED_AC                                        
    On/off control bit for Bobcat AC                                         
****************************************************************************/
#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC__MASK 0x1     
#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC__SHIFT 0x0     
#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC__ADDR 0xb305  
#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_ON 0x1     
#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_OFF 0x0     


/****************************************************************************
   Field SMC_MON_BC_FAN1_STATE                                             
     Input the state of the multiSpeed fan bit 1                             
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_FAN1_STATE__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_FAN1_STATE__SHIFT 0x1     
#define SMC_FPGA_SMC_MON_BC_FAN1_STATE__ADDR 0xb310  


/****************************************************************************
   Field SMC_MON_BC_FAN0_STATE                                             
    Input the state of the multiSpeed fan bit 0                              
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_FAN0_STATE__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_FAN0_STATE__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_BC_FAN0_STATE__ADDR 0xb310  


/****************************************************************************
   Field SMC_MON_BC_PHASE_LOSS                                             
    Phase Loss signal Bobcat 48V supply Low Active                           
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_PHASE_LOSS__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_PHASE_LOSS__SHIFT 0x3     
#define SMC_FPGA_SMC_MON_BC_PHASE_LOSS__ADDR 0xb32b  


/****************************************************************************
   Field SMC_MON_BC_OVR_TMP                                                
    Overtemperature signal Bobcat 48V supply Low Active                      
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_OVR_TMP__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_OVR_TMP__SHIFT 0x2     
#define SMC_FPGA_SMC_MON_BC_OVR_TMP__ADDR 0xb32b  


/****************************************************************************
   Field SMC_MON_BC_AC_PWR_FAULT                                           
    AC power fault Bobcat 48V supply Low Active                              
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT__SHIFT 0x1     
#define SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT__ADDR 0xb32b  


/****************************************************************************
   Field SMC_MON_BC_OUTPUT_FAULT                                           
    Output bad Bobcat 48V supply Low Active                                  
****************************************************************************/
#define SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT__MASK 0x1     
#define SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT__ADDR 0xb32b  


/****************************************************************************
   Field SMC_MON_DC90_48V_ON                                               
    Feedback from the control side of the opto re: the PS state On = High    
****************************************************************************/
#define SMC_FPGA_SMC_MON_DC90_48V_ON__MASK 0x1     
#define SMC_FPGA_SMC_MON_DC90_48V_ON__SHIFT 0x3     
#define SMC_FPGA_SMC_MON_DC90_48V_ON__ADDR 0xb32e  


/****************************************************************************
   Field SMC_MON_DC90_OVR_TMP                                              
    Overtemperature signal DC90 supply Low Active                            
****************************************************************************/
#define SMC_FPGA_SMC_MON_DC90_OVR_TMP__MASK 0x1     
#define SMC_FPGA_SMC_MON_DC90_OVR_TMP__SHIFT 0x2     
#define SMC_FPGA_SMC_MON_DC90_OVR_TMP__ADDR 0xb32e  


/****************************************************************************
   Field SMC_MON_DC90_AC_PWR_FAULT                                         
    AC input fault DC90 supply Low Active                                    
****************************************************************************/
#define SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT__MASK 0x1     
#define SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT__SHIFT 0x1     
#define SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT__ADDR 0xb32e  


/****************************************************************************
   Field SMC_MON_DC90_OUTPUT_FAULT                                         
    Output bad DC90 supply Low Active                                        
****************************************************************************/
#define SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT__MASK 0x1     
#define SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT__SHIFT 0x0     
#define SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT__ADDR 0xb32e  


/****************************************************************************
   Field B_CNTRL_BC_48VDC_DC90                                             
    On/off control bit for Bobcat 48V                                        
****************************************************************************/
#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90__MASK 0x1     
#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90__SHIFT 0x0     
#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90__ADDR 0xb304  
#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90_ON 0x1     
#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90_OFF 0x0     


/****************************************************************************
   Field B_DC90_48V_Enable                                                 
    Enable for On/off control bit for Bobcat DC90 48V                        
****************************************************************************/
#define SMC_FPGA_B_DC90_48V_Enable__MASK 0x1     
#define SMC_FPGA_B_DC90_48V_Enable__SHIFT 0x0     
#define SMC_FPGA_B_DC90_48V_Enable__ADDR 0xb30c  
#define SMC_FPGA_B_DC90_48V_Enable_ENABLE 0x1     
#define SMC_FPGA_B_DC90_48V_Enable_DISABLE 0x0     


/****************************************************************************
   Field B_CNTRL_BC_48VDC                                                  
    On/off control bit for Bobcat 48V                                        
****************************************************************************/
#define SMC_FPGA_B_CNTRL_BC_48VDC__MASK 0x1     
#define SMC_FPGA_B_CNTRL_BC_48VDC__SHIFT 0x0     
#define SMC_FPGA_B_CNTRL_BC_48VDC__ADDR 0xb301  
#define SMC_FPGA_B_CNTRL_BC_48VDC_ON   0x1     
#define SMC_FPGA_B_CNTRL_BC_48VDC_OFF  0x0     


/****************************************************************************
   Field BC_TACH1_LOCK_OUT                                                 
    Lock out state of the GEN_FREQ counter readback                          
****************************************************************************/
#define SMC_FPGA_BC_TACH1_LOCK_OUT__MASK 0x1     
#define SMC_FPGA_BC_TACH1_LOCK_OUT__SHIFT 0x6     
#define SMC_FPGA_BC_TACH1_LOCK_OUT__ADDR 0xb22c  


/****************************************************************************
   Field BC_TACH0_LOCK_OUT                                                 
    Lock out state of the GEN_FREQ counter readback                          
****************************************************************************/
#define SMC_FPGA_BC_TACH0_LOCK_OUT__MASK 0x1     
#define SMC_FPGA_BC_TACH0_LOCK_OUT__SHIFT 0x5     
#define SMC_FPGA_BC_TACH0_LOCK_OUT__ADDR 0xb22c  


/****************************************************************************
   Field GEN_FREQ_LOCK_OUT                                                 
    Lock out state of the GEN_FREQ counter readback                          
****************************************************************************/
#define SMC_FPGA_GEN_FREQ_LOCK_OUT__MASK 0x1     
#define SMC_FPGA_GEN_FREQ_LOCK_OUT__SHIFT 0x4     
#define SMC_FPGA_GEN_FREQ_LOCK_OUT__ADDR 0xb22c  


/****************************************************************************
   Field MAIN_LOCK_OUT                                                     
    Lock out state of the MAIN_BLOWER counter readback                       
****************************************************************************/
#define SMC_FPGA_MAIN_LOCK_OUT__MASK   0x1     
#define SMC_FPGA_MAIN_LOCK_OUT__SHIFT  0x3     
#define SMC_FPGA_MAIN_LOCK_OUT__ADDR   0xb22c  


/****************************************************************************
   Field I2_LOCK_OUT                                                       
    Lock out state of the I2 counter readback                                
****************************************************************************/
#define SMC_FPGA_I2_LOCK_OUT__MASK     0x1     
#define SMC_FPGA_I2_LOCK_OUT__SHIFT    0x2     
#define SMC_FPGA_I2_LOCK_OUT__ADDR     0xb22c  


/****************************************************************************
   Field I1_LOCK_OUT                                                       
    Lock out state of the I1 counter readback                                
****************************************************************************/
#define SMC_FPGA_I1_LOCK_OUT__MASK     0x1     
#define SMC_FPGA_I1_LOCK_OUT__SHIFT    0x1     
#define SMC_FPGA_I1_LOCK_OUT__ADDR     0xb22c  


/****************************************************************************
   Field V0_LOCK_OUT                                                       
    Lock out state of the V0 counter readback                                
****************************************************************************/
#define SMC_FPGA_V0_LOCK_OUT__MASK     0x1     
#define SMC_FPGA_V0_LOCK_OUT__SHIFT    0x0     
#define SMC_FPGA_V0_LOCK_OUT__ADDR     0xb22c  


/****************************************************************************
   Field MAINT_MON                                                         
    Maintainence signal monitor readback                                     
****************************************************************************/
#define SMC_FPGA_MAINT_MON__MASK       0x3     
#define SMC_FPGA_MAINT_MON__SHIFT      0x0     
#define SMC_FPGA_MAINT_MON__ADDR       0xb22b  


/****************************************************************************
   Field ID_REV                                                            
    ID and revision of FPGA                                                  
****************************************************************************/
#define SMC_FPGA_ID_REV__MASK          0xff    
#define SMC_FPGA_ID_REV__SHIFT         0x0     
#define SMC_FPGA_ID_REV__ADDR          0xb22a  


/****************************************************************************
   Field BC_TACH1_CTL                                                      
     Control bit for TACH1 counters                                          
****************************************************************************/
#define SMC_FPGA_BC_TACH1_CTL__MASK    0x1     
#define SMC_FPGA_BC_TACH1_CTL__SHIFT   0x1     
#define SMC_FPGA_BC_TACH1_CTL__ADDR    0xb231  


/****************************************************************************
   Field BC_TACH0_CTL                                                      
     Control bit for TACH0 counters                                          
****************************************************************************/
#define SMC_FPGA_BC_TACH0_CTL__MASK    0x1     
#define SMC_FPGA_BC_TACH0_CTL__SHIFT   0x0     
#define SMC_FPGA_BC_TACH0_CTL__ADDR    0xb231  


/****************************************************************************
   Field BC_TACH1_CTR_HI                                                   
    Readback for upper 8 bits of Bobcat fan 1 frequency counter              
****************************************************************************/
#define SMC_FPGA_BC_TACH1_CTR_HI__MASK 0xff    
#define SMC_FPGA_BC_TACH1_CTR_HI__SHIFT 0x0     
#define SMC_FPGA_BC_TACH1_CTR_HI__ADDR 0xb230  


/****************************************************************************
   Field BC_TACH1_CTR_LO                                                   
    Readback for upper 8 bits of Bobcat fan 1 frequency counter              
****************************************************************************/
#define SMC_FPGA_BC_TACH1_CTR_LO__MASK 0xff    
#define SMC_FPGA_BC_TACH1_CTR_LO__SHIFT 0x0     
#define SMC_FPGA_BC_TACH1_CTR_LO__ADDR 0xb22f  


/****************************************************************************
   Field BC_TACH0_CTR_HI                                                   
    Readback for upper 8 bits of Bobcat fan 0 frequency counter              
****************************************************************************/
#define SMC_FPGA_BC_TACH0_CTR_HI__MASK 0xff    
#define SMC_FPGA_BC_TACH0_CTR_HI__SHIFT 0x0     
#define SMC_FPGA_BC_TACH0_CTR_HI__ADDR 0xb22e  


/****************************************************************************
   Field BC_TACH0_CTR_LO                                                   
    Readback for upper 8 bits of Bobcat fan 0 frequency counter              
****************************************************************************/
#define SMC_FPGA_BC_TACH0_CTR_LO__MASK 0xff    
#define SMC_FPGA_BC_TACH0_CTR_LO__SHIFT 0x0     
#define SMC_FPGA_BC_TACH0_CTR_LO__ADDR 0xb22d  


/****************************************************************************
   Field GEN_FREQ_CTR_HI                                                   
    Readback for upper 8 bits of general purpose frequency counter           
****************************************************************************/
#define SMC_FPGA_GEN_FREQ_CTR_HI__MASK 0xff    
#define SMC_FPGA_GEN_FREQ_CTR_HI__SHIFT 0x0     
#define SMC_FPGA_GEN_FREQ_CTR_HI__ADDR 0xb229  


/****************************************************************************
   Field GEN_FREQ_CTR_MID                                                  
    Readback for middle 8 bits of the general purpose frequency counter      
****************************************************************************/
#define SMC_FPGA_GEN_FREQ_CTR_MID__MASK 0xff    
#define SMC_FPGA_GEN_FREQ_CTR_MID__SHIFT 0x0     
#define SMC_FPGA_GEN_FREQ_CTR_MID__ADDR 0xb226  


/****************************************************************************
   Field GEN_FREQ_CTR_LO                                                   
    Readback for upper 8 bits of the general purpose frequency counter       
****************************************************************************/
#define SMC_FPGA_GEN_FREQ_CTR_LO__MASK 0xff    
#define SMC_FPGA_GEN_FREQ_CTR_LO__SHIFT 0x0     
#define SMC_FPGA_GEN_FREQ_CTR_LO__ADDR 0xb228  


/****************************************************************************
   Field MAIN_BLOWER_HI                                                    
    Readback for upper 8 bits of main blower frequency counter               
****************************************************************************/
#define SMC_FPGA_MAIN_BLOWER_HI__MASK  0xff    
#define SMC_FPGA_MAIN_BLOWER_HI__SHIFT 0x0     
#define SMC_FPGA_MAIN_BLOWER_HI__ADDR  0xb21f  


/****************************************************************************
   Field MAIN_BLOWER_LO                                                    
    Readback for upper 8 bits of main blower frequency counter               
****************************************************************************/
#define SMC_FPGA_MAIN_BLOWER_LO__MASK  0xff    
#define SMC_FPGA_MAIN_BLOWER_LO__SHIFT 0x0     
#define SMC_FPGA_MAIN_BLOWER_LO__ADDR  0xb21e  


/****************************************************************************
   Field I2_HI                                                             
    Readback for upper 8 bits of I2 frequency counter                        
****************************************************************************/
#define SMC_FPGA_I2_HI__MASK           0xff    
#define SMC_FPGA_I2_HI__SHIFT          0x0     
#define SMC_FPGA_I2_HI__ADDR           0xb213  


/****************************************************************************
   Field I2_LO                                                             
    Readback for low 8 bits of I2 frequency counter                          
****************************************************************************/
#define SMC_FPGA_I2_LO__MASK           0xff    
#define SMC_FPGA_I2_LO__SHIFT          0x0     
#define SMC_FPGA_I2_LO__ADDR           0xb212  


/****************************************************************************
   Field I1_HI                                                             
    Readback for upper 8 bits of I1 frequency counter                        
****************************************************************************/
#define SMC_FPGA_I1_HI__MASK           0xff    
#define SMC_FPGA_I1_HI__SHIFT          0x0     
#define SMC_FPGA_I1_HI__ADDR           0xb211  


/****************************************************************************
   Field I1_LO                                                             
    Readback for low 8 bits of I1 frequency counter                          
****************************************************************************/
#define SMC_FPGA_I1_LO__MASK           0xff    
#define SMC_FPGA_I1_LO__SHIFT          0x0     
#define SMC_FPGA_I1_LO__ADDR           0xb210  


/****************************************************************************
   Field V0_HI                                                             
    Readback for upper 8 bits of V0 frequency counter                        
****************************************************************************/
#define SMC_FPGA_V0_HI__MASK           0xff    
#define SMC_FPGA_V0_HI__SHIFT          0x0     
#define SMC_FPGA_V0_HI__ADDR           0xb20b  


/****************************************************************************
   Field V0_LO                                                             
    Readback for low 8 bits of V0 frequency counter                          
****************************************************************************/
#define SMC_FPGA_V0_LO__MASK           0xff    
#define SMC_FPGA_V0_LO__SHIFT          0x0     
#define SMC_FPGA_V0_LO__ADDR           0xb20a  


/****************************************************************************
   Field GEN_FREQ_CTR_MUX                                                  
    General purpose frequency counter input select                           
****************************************************************************/
#define SMC_FPGA_GEN_FREQ_CTR_MUX__MASK 0x1f    
#define SMC_FPGA_GEN_FREQ_CTR_MUX__SHIFT 0x0     
#define SMC_FPGA_GEN_FREQ_CTR_MUX__ADDR 0xb227  
#define SMC_FPGA_GEN_FREQ_CTR_MUX_SC_FAN 0x10    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_V1 0x11    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_V2 0x12    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_K1_ON 0x13    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_SPU_FAN 0x14    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_VAB 0x15    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_VAC 0x16    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_VBC 0x17    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_FREQ 0x18    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_48V_ON 0x19    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_SMC_SPR2_FAN_IN_MON 0x1a    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_48V_ON 0x00    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_K1_ON 0x01    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_BC_FAN0_TACH 0x02    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_BC_FAN1_TACH 0x03    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_AUX2 0x04    
#define SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_AUX3 0x05    


/****************************************************************************
   Field CTR_CTL                                                           
    frequency counter enable                                                 
****************************************************************************/
#define SMC_FPGA_CTR_CTL__MASK         0x1     
#define SMC_FPGA_CTR_CTL__SHIFT        0x0     
#define SMC_FPGA_CTR_CTL__ADDR         0xb209  
#define SMC_FPGA_CTR_CTL_ENABLE        0x1     
#define SMC_FPGA_CTR_CTL_DISABLE       0x0     


/****************************************************************************
   Field CLR_LOCK_OUT                                                      
    Reset lock_out signals for all counters                                  
****************************************************************************/
#define SMC_FPGA_CLR_LOCK_OUT__MASK    0x1     
#define SMC_FPGA_CLR_LOCK_OUT__SHIFT   0x3     
#define SMC_FPGA_CLR_LOCK_OUT__ADDR    0xb208  
#define SMC_FPGA_CLR_LOCK_OUT_CLR      0x1     
#define SMC_FPGA_CLR_LOCK_OUT_NORMAL   0x0     


/****************************************************************************
   Field CLR_MAINT_REG                                                     
    Reset Maint signal change register                                       
****************************************************************************/
#define SMC_FPGA_CLR_MAINT_REG__MASK   0x1     
#define SMC_FPGA_CLR_MAINT_REG__SHIFT  0x2     
#define SMC_FPGA_CLR_MAINT_REG__ADDR   0xb208  
#define SMC_FPGA_CLR_MAINT_REG_CLR     0x1     
#define SMC_FPGA_CLR_MAINT_REG_NORMAL  0x0     


/****************************************************************************
   Field CLR_REGS                                                          
    Reset all frequency counter output registers                             
****************************************************************************/
#define SMC_FPGA_CLR_REGS__MASK        0x1     
#define SMC_FPGA_CLR_REGS__SHIFT       0x1     
#define SMC_FPGA_CLR_REGS__ADDR        0xb208  
#define SMC_FPGA_CLR_REGS_CLR          0x1     
#define SMC_FPGA_CLR_REGS_COUNT        0x0     


/****************************************************************************
   Field CLR_CTRS                                                          
    Reset all frequency counters                                             
****************************************************************************/
#define SMC_FPGA_CLR_CTRS__MASK        0x1     
#define SMC_FPGA_CLR_CTRS__SHIFT       0x0     
#define SMC_FPGA_CLR_CTRS__ADDR        0xb208  
#define SMC_FPGA_CLR_CTRS_CLR          0x1     
#define SMC_FPGA_CLR_CTRS_COUNT        0x0     


/****************************************************************************
   Field AUX_3_CTL                                                         
    On/off control bits for Auxiliary 3 output                               
****************************************************************************/
#define SMC_FPGA_AUX_3_CTL__MASK       0x3     
#define SMC_FPGA_AUX_3_CTL__SHIFT      0x0     
#define SMC_FPGA_AUX_3_CTL__ADDR       0xb207  
#define SMC_FPGA_AUX_3_CTL_ON          0x1     
#define SMC_FPGA_AUX_3_CTL_OFF         0x0     
#define SMC_FPGA_AUX_3_CTL_LOW         0x3     


/****************************************************************************
   Field AUX_2_CTL                                                         
    On/off control bits for Auxiliary 2 output                               
****************************************************************************/
#define SMC_FPGA_AUX_2_CTL__MASK       0x3     
#define SMC_FPGA_AUX_2_CTL__SHIFT      0x0     
#define SMC_FPGA_AUX_2_CTL__ADDR       0xb206  
#define SMC_FPGA_AUX_2_CTL_ON          0x1     
#define SMC_FPGA_AUX_2_CTL_OFF         0x0     
#define SMC_FPGA_AUX_2_CTL_LOW         0x3     


/****************************************************************************
   Field AUX_1_CTL                                                         
    On/off control bits for Auxiliary 1 output                               
****************************************************************************/
#define SMC_FPGA_AUX_1_CTL__MASK       0x3     
#define SMC_FPGA_AUX_1_CTL__SHIFT      0x0     
#define SMC_FPGA_AUX_1_CTL__ADDR       0xb205  
#define SMC_FPGA_AUX_1_CTL_ON          0x1     
#define SMC_FPGA_AUX_1_CTL_OFF         0x0     
#define SMC_FPGA_AUX_1_CTL_LOW         0x3     


/****************************************************************************
   Field AUX_0_CTL                                                         
    On/off control bits for Auxiliary 0 output                               
****************************************************************************/
#define SMC_FPGA_AUX_0_CTL__MASK       0x3     
#define SMC_FPGA_AUX_0_CTL__SHIFT      0x0     
#define SMC_FPGA_AUX_0_CTL__ADDR       0xb204  
#define SMC_FPGA_AUX_0_CTL_ON          0x1     
#define SMC_FPGA_AUX_0_CTL_OFF         0x0     
#define SMC_FPGA_AUX_0_CTL_LOW         0x3     


/****************************************************************************
   Field AUX_FAN_CTL                                                       
    On/off control bits for Auxiliary fan output                             
****************************************************************************/
#define SMC_FPGA_AUX_FAN_CTL__MASK     0x3     
#define SMC_FPGA_AUX_FAN_CTL__SHIFT    0x0     
#define SMC_FPGA_AUX_FAN_CTL__ADDR     0xb203  
#define SMC_FPGA_AUX_FAN_CTL_ON        0x1     
#define SMC_FPGA_AUX_FAN_CTL_OFF       0x0     
#define SMC_FPGA_AUX_FAN_CTL_LOW       0x3     


/****************************************************************************
   Field K1_ENABLE                                                         
    Enable for On/off control bit for K1                                     
****************************************************************************/
#define SMC_FPGA_K1_ENABLE__MASK       0x1     
#define SMC_FPGA_K1_ENABLE__SHIFT      0x0     
#define SMC_FPGA_K1_ENABLE__ADDR       0xb20d  
#define SMC_FPGA_K1_ENABLE_ENABLE      0x1     
#define SMC_FPGA_K1_ENABLE_DISABLE     0x0     


/****************************************************************************
   Field K1_ON                                                             
    On/off control bit for K1                                                
****************************************************************************/
#define SMC_FPGA_K1_ON__MASK           0x1     
#define SMC_FPGA_K1_ON__SHIFT          0x0     
#define SMC_FPGA_K1_ON__ADDR           0xb202  
#define SMC_FPGA_K1_ON_ON              0x1     
#define SMC_FPGA_K1_ON_OFF             0x0     


/****************************************************************************
   Field V48_ENABLE                                                        
    Enable for On/off control bit for 48V                                    
****************************************************************************/
#define SMC_FPGA_V48_ENABLE__MASK      0x1     
#define SMC_FPGA_V48_ENABLE__SHIFT     0x0     
#define SMC_FPGA_V48_ENABLE__ADDR      0xb20c  
#define SMC_FPGA_V48_ENABLE_ENABLE     0x1     
#define SMC_FPGA_V48_ENABLE_DISABLE    0x0     


/****************************************************************************
   Field V48_ON                                                            
    On/off control bit for 48V                                               
****************************************************************************/
#define SMC_FPGA_V48_ON__MASK          0x1     
#define SMC_FPGA_V48_ON__SHIFT         0x0     
#define SMC_FPGA_V48_ON__ADDR          0xb201  
#define SMC_FPGA_V48_ON_ON             0x1     
#define SMC_FPGA_V48_ON_OFF            0x0     




/****************************************************************************
   Writes for Instrument SMC_FPGA
****************************************************************************/


#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_B_CNTRL_BC_48VDC_DC90, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_B_DC90_48V_ENABLE_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_B_DC90_48V_Enable, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_B_CNTRL_BC_48VDC_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_B_CNTRL_BC_48VDC, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_BC_TACH1_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_BC_TACH_CTL, 0x2, (data & 0x1)<<1, tl_tcio_32r, tl_tcio_32w, (IDL_SOFTRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_BC_TACH0_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_BC_TACH_CTL, 0x1, (data & 0x1), tl_tcio_32r, tl_tcio_32w, (IDL_SOFTRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_GEN_FREQ_CTR_MUX_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_GEN_FREQ_CTR_MUX, 0x1f, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_CTR_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_CTR_CTL, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_CLR_LOCK_OUT_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_RESET, 0x8, (data & 0x1)<<3, tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_RMW))

#define SMC_FPGA_CLR_MAINT_REG_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_RESET, 0x4, (data & 0x1)<<2, tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_RMW))

#define SMC_FPGA_CLR_REGS_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_RESET, 0x2, (data & 0x1)<<1, tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_RMW))

#define SMC_FPGA_CLR_CTRS_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_RESET, 0x1, (data & 0x1), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_RMW))

#define SMC_FPGA_AUX_3_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_AUX_3_CTL, 0x3, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_AUX_2_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_AUX_2_CTL, 0x3, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_AUX_1_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_AUX_1_CTL, 0x3, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_AUX_0_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_AUX_0_CTL, 0x3, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_AUX_FAN_CTL_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_AUX_FAN_CTL, 0x3, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_K1_ENABLE_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_K1_ENABLE, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_K1_ON_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_K1_ON, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_V48_ENABLE_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_V48_ENABLE, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))

#define SMC_FPGA_V48_ON_W( data ) \
 tl_idl_w(tl_smc_fpga_regs, SMC_FPGA_V48_ON, 0x1, (data), tl_tcio_32r, tl_tcio_32w, (IDL_HADRRB | IDL_NOSTORE | IDL_NORMW))


/****************************************************************************
   Reads for Instrument SMC_FPGA
****************************************************************************/


#define SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_PDU_K1_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_MON_PDU_K1, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_BC_AC_ON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_SMC_MON_BC_AC_ON, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_BC_FAN1_STATE_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_STATE_BC_FAN, tl_tcio_32r, IDL_HADRRB)>> 1) & 0x1)

#define SMC_FPGA_SMC_MON_BC_FAN0_STATE_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_STATE_BC_FAN, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_BC_PHASE_LOSS_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_STATE_48V, tl_tcio_32r, IDL_HADRRB)>> 3) & 0x1)

#define SMC_FPGA_SMC_MON_BC_OVR_TMP_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_STATE_48V, tl_tcio_32r, IDL_HADRRB)>> 2) & 0x1)

#define SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_STATE_48V, tl_tcio_32r, IDL_HADRRB)>> 1) & 0x1)

#define SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_STATE_48V, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_SMC_MON_DC90_48V_ON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_DC90_STATE, tl_tcio_32r, IDL_HADRRB)>> 3) & 0x1)

#define SMC_FPGA_SMC_MON_DC90_OVR_TMP_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_DC90_STATE, tl_tcio_32r, IDL_HADRRB)>> 2) & 0x1)

#define SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_DC90_STATE, tl_tcio_32r, IDL_HADRRB)>> 1) & 0x1)

#define SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_DC90_STATE, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_B_CNTRL_BC_48VDC_DC90_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_B_CNTRL_BC_48VDC_DC90, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_B_DC90_48V_ENABLE_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_B_DC90_48V_Enable, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_B_CNTRL_BC_48VDC_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_B_CNTRL_BC_48VDC, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_BC_TACH1_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)>> 6) & 0x1)

#define SMC_FPGA_BC_TACH0_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)>> 5) & 0x1)

#define SMC_FPGA_GEN_FREQ_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)>> 4) & 0x1)

#define SMC_FPGA_MAIN_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)>> 3) & 0x1)

#define SMC_FPGA_I2_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)>> 2) & 0x1)

#define SMC_FPGA_I1_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)>> 1) & 0x1)

#define SMC_FPGA_V0_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_LOCK_OUT_STATE, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_MAINT_MON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_MAINT_MON, tl_tcio_32r, IDL_HADRRB)) & 0x3)

#define SMC_FPGA_ID_REV_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_ID_REV, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_BC_TACH1_CTR_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_BC_TACH1_CTR_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_BC_TACH1_CTR_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_BC_TACH1_CTR_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_BC_TACH0_CTR_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_BC_TACH0_CTR_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_BC_TACH0_CTR_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_BC_TACH0_CTR_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_GEN_FREQ_CTR_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_GEN_FREQ_CTR_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_GEN_FREQ_CTR_MID_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_GEN_FREQ_CTR_MID, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_GEN_FREQ_CTR_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_GEN_FREQ_CTR_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_MAIN_BLOWER_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_MAIN_BLOWER_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_MAIN_BLOWER_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_MAIN_BLOWER_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_I2_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_I2_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_I2_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_I2_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_I1_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_I1_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_I1_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_I1_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_V0_HI_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_V0_HI, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_V0_LO_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_V0_LO, tl_tcio_32r, IDL_HADRRB)) & 0xff)

#define SMC_FPGA_GEN_FREQ_CTR_MUX_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_GEN_FREQ_CTR_MUX, tl_tcio_32r, IDL_HADRRB)) & 0x1f)

#define SMC_FPGA_CTR_CTL_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_CTR_CTL, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_CLR_LOCK_OUT_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_RESET, tl_tcio_32r, IDL_HADRRB)>> 3) & 0x1)

#define SMC_FPGA_CLR_MAINT_REG_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_RESET, tl_tcio_32r, IDL_HADRRB)>> 2) & 0x1)

#define SMC_FPGA_CLR_REGS_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_RESET, tl_tcio_32r, IDL_HADRRB)>> 1) & 0x1)

#define SMC_FPGA_CLR_CTRS_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_RESET, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_AUX_3_CTL_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_AUX_3_CTL, tl_tcio_32r, IDL_HADRRB)) & 0x3)

#define SMC_FPGA_AUX_2_CTL_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_AUX_2_CTL, tl_tcio_32r, IDL_HADRRB)) & 0x3)

#define SMC_FPGA_AUX_1_CTL_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_AUX_1_CTL, tl_tcio_32r, IDL_HADRRB)) & 0x3)

#define SMC_FPGA_AUX_0_CTL_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_AUX_0_CTL, tl_tcio_32r, IDL_HADRRB)) & 0x3)

#define SMC_FPGA_AUX_FAN_CTL_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_AUX_FAN_CTL, tl_tcio_32r, IDL_HADRRB)) & 0x3)

#define SMC_FPGA_K1_ENABLE_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_K1_ENABLE, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_K1_ON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_K1_ON, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_V48_ENABLE_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_V48_ENABLE, tl_tcio_32r, IDL_HADRRB)) & 0x1)

#define SMC_FPGA_V48_ON_R( ) \
  ((tl_idl_r(tl_smc_fpga_regs, SMC_FPGA_V48_ON, tl_tcio_32r, IDL_HADRRB)) & 0x1)
#endif
