'' ****************************************************************************

''  Visual Basic HEADER FILE FOR INSTRUMENT SMC_FPGA

''   PREPARED BY IDL VERSION 2.30e 

''   DO NOT EDIT THIS FILE-YOU'LL LOSE THE ABILITY TO RERUN IDL

'' ****************************************************************************


'   Field SMC_MON_PDU_JAG_THERMAL_FAULT                                     
'    Thermal Fault output from 48V Jag Power Supply                           
public const SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT__ADDR as long= &hB30A&
public const SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT__SHIFT as long= &h0&

'   Field SMC_MON_PDU_JAG_48V_LVL_ON                                        
'     Used on Jaguar this is feedback for the control Input Signal, On=Low    
public const SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON__ADDR as long= &hB32C&
public const SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON__SHIFT as long= &h0&

'   Field SMC_MON_PDU_JAG_48V_GOOD                                          
'    BOBCAT 48V interlock OK = Low, Jag output OK OK = HIGH                   
public const SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD__ADDR as long= &hB311&
public const SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD__SHIFT as long= &h0&

'   Field SMC_CNTRL_JAG_48VDC_ON                                            
'    On/off control bit for Jaguar 48V                                        
public const SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON__ADDR as long= &hB306&
public const SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON__MASK as long= &h1&
public const SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON__SHIFT as long= &h0&
public const SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_ON as long = &H1&
public const SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_OFF as long = &H0&

'   Field SMC_MON_PDU_K1                                                    
'    On/off control readback bit for K1                                       
public const SMC_FPGA_SMC_MON_PDU_K1__ADDR as long= &hB303&
public const SMC_FPGA_SMC_MON_PDU_K1__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_PDU_K1__SHIFT as long= &h0&
public const SMC_FPGA_SMC_MON_PDU_K1_CLR as long = &H0&

'   Field SMC_CNTRL_JAG_SWITCHED_AC                                         
'    On/off control bit for Jaguar AC                                         
public const SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC__ADDR as long= &hB302&
public const SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC__MASK as long= &h1&
public const SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC__SHIFT as long= &h0&
public const SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_ON as long = &H1&
public const SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_OFF as long = &H0&

'   Field SMC_MON_BC_AC_ON                                                  
'    On/off control readback bit for K1                                       
public const SMC_FPGA_SMC_MON_BC_AC_ON__ADDR as long= &hB32A&
public const SMC_FPGA_SMC_MON_BC_AC_ON__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_AC_ON__SHIFT as long= &h0&

'   Field B_SMC_CNTRL_BC_SWITCHED_AC                                        
'    On/off control bit for Bobcat AC                                         
public const SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC__ADDR as long= &hB305&
public const SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC__MASK as long= &h1&
public const SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC__SHIFT as long= &h0&
public const SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_ON as long = &H1&
public const SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_OFF as long = &H0&

'   Field SMC_MON_BC_FAN1_STATE                                             
'     Input the state of the multiSpeed fan bit 1                             
public const SMC_FPGA_SMC_MON_BC_FAN1_STATE__ADDR as long= &hB310&
public const SMC_FPGA_SMC_MON_BC_FAN1_STATE__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_FAN1_STATE__SHIFT as long= &h1&

'   Field SMC_MON_BC_FAN0_STATE                                             
'    Input the state of the multiSpeed fan bit 0                              
public const SMC_FPGA_SMC_MON_BC_FAN0_STATE__ADDR as long= &hB310&
public const SMC_FPGA_SMC_MON_BC_FAN0_STATE__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_FAN0_STATE__SHIFT as long= &h0&

'   Field SMC_MON_BC_PHASE_LOSS                                             
'    Phase Loss signal Bobcat 48V supply Low Active                           
public const SMC_FPGA_SMC_MON_BC_PHASE_LOSS__ADDR as long= &hB32B&
public const SMC_FPGA_SMC_MON_BC_PHASE_LOSS__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_PHASE_LOSS__SHIFT as long= &h3&

'   Field SMC_MON_BC_OVR_TMP                                                
'    Overtemperature signal Bobcat 48V supply Low Active                      
public const SMC_FPGA_SMC_MON_BC_OVR_TMP__ADDR as long= &hB32B&
public const SMC_FPGA_SMC_MON_BC_OVR_TMP__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_OVR_TMP__SHIFT as long= &h2&

'   Field SMC_MON_BC_AC_PWR_FAULT                                           
'    AC power fault Bobcat 48V supply Low Active                              
public const SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT__ADDR as long= &hB32B&
public const SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT__SHIFT as long= &h1&

'   Field SMC_MON_BC_OUTPUT_FAULT                                           
'    Output bad Bobcat 48V supply Low Active                                  
public const SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT__ADDR as long= &hB32B&
public const SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT__SHIFT as long= &h0&

'   Field SMC_MON_DC90_48V_ON                                               
'    Feedback from the control side of the opto re: the PS state On = High    
public const SMC_FPGA_SMC_MON_DC90_48V_ON__ADDR as long= &hB32E&
public const SMC_FPGA_SMC_MON_DC90_48V_ON__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_DC90_48V_ON__SHIFT as long= &h3&

'   Field SMC_MON_DC90_OVR_TMP                                              
'    Overtemperature signal DC90 supply Low Active                            
public const SMC_FPGA_SMC_MON_DC90_OVR_TMP__ADDR as long= &hB32E&
public const SMC_FPGA_SMC_MON_DC90_OVR_TMP__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_DC90_OVR_TMP__SHIFT as long= &h2&

'   Field SMC_MON_DC90_AC_PWR_FAULT                                         
'    AC input fault DC90 supply Low Active                                    
public const SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT__ADDR as long= &hB32E&
public const SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT__SHIFT as long= &h1&

'   Field SMC_MON_DC90_OUTPUT_FAULT                                         
'    Output bad DC90 supply Low Active                                        
public const SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT__ADDR as long= &hB32E&
public const SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT__MASK as long= &h1&
public const SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT__SHIFT as long= &h0&

'   Field B_CNTRL_BC_48VDC_DC90                                             
'    On/off control bit for Bobcat 48V                                        
public const SMC_FPGA_B_CNTRL_BC_48VDC_DC90__ADDR as long= &hB304&
public const SMC_FPGA_B_CNTRL_BC_48VDC_DC90__MASK as long= &h1&
public const SMC_FPGA_B_CNTRL_BC_48VDC_DC90__SHIFT as long= &h0&
public const SMC_FPGA_B_CNTRL_BC_48VDC_DC90_ON as long = &H1&
public const SMC_FPGA_B_CNTRL_BC_48VDC_DC90_OFF as long = &H0&

'   Field B_DC90_48V_Enable                                                 
'    Enable for On/off control bit for Bobcat DC90 48V                        
public const SMC_FPGA_B_DC90_48V_Enable__ADDR as long= &hB30C&
public const SMC_FPGA_B_DC90_48V_Enable__MASK as long= &h1&
public const SMC_FPGA_B_DC90_48V_Enable__SHIFT as long= &h0&
public const SMC_FPGA_B_DC90_48V_Enable_ENABLE as long = &H1&
public const SMC_FPGA_B_DC90_48V_Enable_DISABLE as long = &H0&

'   Field B_CNTRL_BC_48VDC                                                  
'    On/off control bit for Bobcat 48V                                        
public const SMC_FPGA_B_CNTRL_BC_48VDC__ADDR as long= &hB301&
public const SMC_FPGA_B_CNTRL_BC_48VDC__MASK as long= &h1&
public const SMC_FPGA_B_CNTRL_BC_48VDC__SHIFT as long= &h0&
public const SMC_FPGA_B_CNTRL_BC_48VDC_ON as long = &H1&
public const SMC_FPGA_B_CNTRL_BC_48VDC_OFF as long = &H0&

'   Field BC_TACH1_LOCK_OUT                                                 
'    Lock out state of the GEN_FREQ counter readback                          
public const SMC_FPGA_BC_TACH1_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_BC_TACH1_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_BC_TACH1_LOCK_OUT__SHIFT as long= &h6&

'   Field BC_TACH0_LOCK_OUT                                                 
'    Lock out state of the GEN_FREQ counter readback                          
public const SMC_FPGA_BC_TACH0_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_BC_TACH0_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_BC_TACH0_LOCK_OUT__SHIFT as long= &h5&

'   Field GEN_FREQ_LOCK_OUT                                                 
'    Lock out state of the GEN_FREQ counter readback                          
public const SMC_FPGA_GEN_FREQ_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_GEN_FREQ_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_GEN_FREQ_LOCK_OUT__SHIFT as long= &h4&

'   Field MAIN_LOCK_OUT                                                     
'    Lock out state of the MAIN_BLOWER counter readback                       
public const SMC_FPGA_MAIN_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_MAIN_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_MAIN_LOCK_OUT__SHIFT as long= &h3&

'   Field I2_LOCK_OUT                                                       
'    Lock out state of the I2 counter readback                                
public const SMC_FPGA_I2_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_I2_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_I2_LOCK_OUT__SHIFT as long= &h2&

'   Field I1_LOCK_OUT                                                       
'    Lock out state of the I1 counter readback                                
public const SMC_FPGA_I1_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_I1_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_I1_LOCK_OUT__SHIFT as long= &h1&

'   Field V0_LOCK_OUT                                                       
'    Lock out state of the V0 counter readback                                
public const SMC_FPGA_V0_LOCK_OUT__ADDR as long= &hB22C&
public const SMC_FPGA_V0_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_V0_LOCK_OUT__SHIFT as long= &h0&

'   Field MAINT_MON                                                         
'    Maintainence signal monitor readback                                     
public const SMC_FPGA_MAINT_MON__ADDR as long= &hB22B&
public const SMC_FPGA_MAINT_MON__MASK as long= &h3&
public const SMC_FPGA_MAINT_MON__SHIFT as long= &h0&

'   Field ID_REV                                                            
'    ID and revision of FPGA                                                  
public const SMC_FPGA_ID_REV__ADDR as long= &hB22A&
public const SMC_FPGA_ID_REV__MASK as long= &hFF&
public const SMC_FPGA_ID_REV__SHIFT as long= &h0&

'   Field BC_TACH1_CTL                                                      
'     Control bit for TACH1 counters                                          
public const SMC_FPGA_BC_TACH1_CTL__ADDR as long= &hB231&
public const SMC_FPGA_BC_TACH1_CTL__MASK as long= &h1&
public const SMC_FPGA_BC_TACH1_CTL__SHIFT as long= &h1&

'   Field BC_TACH0_CTL                                                      
'     Control bit for TACH0 counters                                          
public const SMC_FPGA_BC_TACH0_CTL__ADDR as long= &hB231&
public const SMC_FPGA_BC_TACH0_CTL__MASK as long= &h1&
public const SMC_FPGA_BC_TACH0_CTL__SHIFT as long= &h0&

'   Field BC_TACH1_CTR_HI                                                   
'    Readback for upper 8 bits of Bobcat fan 1 frequency counter              
public const SMC_FPGA_BC_TACH1_CTR_HI__ADDR as long= &hB230&
public const SMC_FPGA_BC_TACH1_CTR_HI__MASK as long= &hFF&
public const SMC_FPGA_BC_TACH1_CTR_HI__SHIFT as long= &h0&

'   Field BC_TACH1_CTR_LO                                                   
'    Readback for upper 8 bits of Bobcat fan 1 frequency counter              
public const SMC_FPGA_BC_TACH1_CTR_LO__ADDR as long= &hB22F&
public const SMC_FPGA_BC_TACH1_CTR_LO__MASK as long= &hFF&
public const SMC_FPGA_BC_TACH1_CTR_LO__SHIFT as long= &h0&

'   Field BC_TACH0_CTR_HI                                                   
'    Readback for upper 8 bits of Bobcat fan 0 frequency counter              
public const SMC_FPGA_BC_TACH0_CTR_HI__ADDR as long= &hB22E&
public const SMC_FPGA_BC_TACH0_CTR_HI__MASK as long= &hFF&
public const SMC_FPGA_BC_TACH0_CTR_HI__SHIFT as long= &h0&

'   Field BC_TACH0_CTR_LO                                                   
'    Readback for upper 8 bits of Bobcat fan 0 frequency counter              
public const SMC_FPGA_BC_TACH0_CTR_LO__ADDR as long= &hB22D&
public const SMC_FPGA_BC_TACH0_CTR_LO__MASK as long= &hFF&
public const SMC_FPGA_BC_TACH0_CTR_LO__SHIFT as long= &h0&

'   Field GEN_FREQ_CTR_HI                                                   
'    Readback for upper 8 bits of general purpose frequency counter           
public const SMC_FPGA_GEN_FREQ_CTR_HI__ADDR as long= &hB229&
public const SMC_FPGA_GEN_FREQ_CTR_HI__MASK as long= &hFF&
public const SMC_FPGA_GEN_FREQ_CTR_HI__SHIFT as long= &h0&

'   Field GEN_FREQ_CTR_MID                                                  
'    Readback for middle 8 bits of the general purpose frequency counter      
public const SMC_FPGA_GEN_FREQ_CTR_MID__ADDR as long= &hB226&
public const SMC_FPGA_GEN_FREQ_CTR_MID__MASK as long= &hFF&
public const SMC_FPGA_GEN_FREQ_CTR_MID__SHIFT as long= &h0&

'   Field GEN_FREQ_CTR_LO                                                   
'    Readback for upper 8 bits of the general purpose frequency counter       
public const SMC_FPGA_GEN_FREQ_CTR_LO__ADDR as long= &hB228&
public const SMC_FPGA_GEN_FREQ_CTR_LO__MASK as long= &hFF&
public const SMC_FPGA_GEN_FREQ_CTR_LO__SHIFT as long= &h0&

'   Field MAIN_BLOWER_HI                                                    
'    Readback for upper 8 bits of main blower frequency counter               
public const SMC_FPGA_MAIN_BLOWER_HI__ADDR as long= &hB21F&
public const SMC_FPGA_MAIN_BLOWER_HI__MASK as long= &hFF&
public const SMC_FPGA_MAIN_BLOWER_HI__SHIFT as long= &h0&

'   Field MAIN_BLOWER_LO                                                    
'    Readback for upper 8 bits of main blower frequency counter               
public const SMC_FPGA_MAIN_BLOWER_LO__ADDR as long= &hB21E&
public const SMC_FPGA_MAIN_BLOWER_LO__MASK as long= &hFF&
public const SMC_FPGA_MAIN_BLOWER_LO__SHIFT as long= &h0&

'   Field I2_HI                                                             
'    Readback for upper 8 bits of I2 frequency counter                        
public const SMC_FPGA_I2_HI__ADDR as long= &hB213&
public const SMC_FPGA_I2_HI__MASK as long= &hFF&
public const SMC_FPGA_I2_HI__SHIFT as long= &h0&

'   Field I2_LO                                                             
'    Readback for low 8 bits of I2 frequency counter                          
public const SMC_FPGA_I2_LO__ADDR as long= &hB212&
public const SMC_FPGA_I2_LO__MASK as long= &hFF&
public const SMC_FPGA_I2_LO__SHIFT as long= &h0&

'   Field I1_HI                                                             
'    Readback for upper 8 bits of I1 frequency counter                        
public const SMC_FPGA_I1_HI__ADDR as long= &hB211&
public const SMC_FPGA_I1_HI__MASK as long= &hFF&
public const SMC_FPGA_I1_HI__SHIFT as long= &h0&

'   Field I1_LO                                                             
'    Readback for low 8 bits of I1 frequency counter                          
public const SMC_FPGA_I1_LO__ADDR as long= &hB210&
public const SMC_FPGA_I1_LO__MASK as long= &hFF&
public const SMC_FPGA_I1_LO__SHIFT as long= &h0&

'   Field V0_HI                                                             
'    Readback for upper 8 bits of V0 frequency counter                        
public const SMC_FPGA_V0_HI__ADDR as long= &hB20B&
public const SMC_FPGA_V0_HI__MASK as long= &hFF&
public const SMC_FPGA_V0_HI__SHIFT as long= &h0&

'   Field V0_LO                                                             
'    Readback for low 8 bits of V0 frequency counter                          
public const SMC_FPGA_V0_LO__ADDR as long= &hB20A&
public const SMC_FPGA_V0_LO__MASK as long= &hFF&
public const SMC_FPGA_V0_LO__SHIFT as long= &h0&

'   Field GEN_FREQ_CTR_MUX                                                  
'    General purpose frequency counter input select                           
public const SMC_FPGA_GEN_FREQ_CTR_MUX__ADDR as long= &hB227&
public const SMC_FPGA_GEN_FREQ_CTR_MUX__MASK as long= &h1F&
public const SMC_FPGA_GEN_FREQ_CTR_MUX__SHIFT as long= &h0&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_SC_FAN as long = &H10&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_V1 as long = &H11&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_V2 as long = &H12&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_K1_ON as long = &H13&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_SPU_FAN as long = &H14&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_VAB as long = &H15&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_VAC as long = &H16&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_VBC as long = &H17&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_FREQ as long = &H18&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_PDU_48V_ON as long = &H19&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_SMC_SPR2_FAN_IN_MON as long = &H1A&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_48V_ON as long = &H0&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_K1_ON as long = &H1&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_BC_FAN0_TACH as long = &H2&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_BC_FAN1_TACH as long = &H3&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_AUX2 as long = &H4&
public const SMC_FPGA_GEN_FREQ_CTR_MUX_FPGA_AUX3 as long = &H5&

'   Field CTR_CTL                                                           
'    frequency counter enable                                                 
public const SMC_FPGA_CTR_CTL__ADDR as long= &hB209&
public const SMC_FPGA_CTR_CTL__MASK as long= &h1&
public const SMC_FPGA_CTR_CTL__SHIFT as long= &h0&
public const SMC_FPGA_CTR_CTL_ENABLE as long = &H1&
public const SMC_FPGA_CTR_CTL_DISABLE as long = &H0&

'   Field CLR_LOCK_OUT                                                      
'    Reset lock_out signals for all counters                                  
public const SMC_FPGA_CLR_LOCK_OUT__ADDR as long= &hB208&
public const SMC_FPGA_CLR_LOCK_OUT__MASK as long= &h1&
public const SMC_FPGA_CLR_LOCK_OUT__SHIFT as long= &h3&
public const SMC_FPGA_CLR_LOCK_OUT_CLR as long = &H1&
public const SMC_FPGA_CLR_LOCK_OUT_NORMAL as long = &H0&

'   Field CLR_MAINT_REG                                                     
'    Reset Maint signal change register                                       
public const SMC_FPGA_CLR_MAINT_REG__ADDR as long= &hB208&
public const SMC_FPGA_CLR_MAINT_REG__MASK as long= &h1&
public const SMC_FPGA_CLR_MAINT_REG__SHIFT as long= &h2&
public const SMC_FPGA_CLR_MAINT_REG_CLR as long = &H1&
public const SMC_FPGA_CLR_MAINT_REG_NORMAL as long = &H0&

'   Field CLR_REGS                                                          
'    Reset all frequency counter output registers                             
public const SMC_FPGA_CLR_REGS__ADDR as long= &hB208&
public const SMC_FPGA_CLR_REGS__MASK as long= &h1&
public const SMC_FPGA_CLR_REGS__SHIFT as long= &h1&
public const SMC_FPGA_CLR_REGS_CLR as long = &H1&
public const SMC_FPGA_CLR_REGS_COUNT as long = &H0&

'   Field CLR_CTRS                                                          
'    Reset all frequency counters                                             
public const SMC_FPGA_CLR_CTRS__ADDR as long= &hB208&
public const SMC_FPGA_CLR_CTRS__MASK as long= &h1&
public const SMC_FPGA_CLR_CTRS__SHIFT as long= &h0&
public const SMC_FPGA_CLR_CTRS_CLR as long = &H1&
public const SMC_FPGA_CLR_CTRS_COUNT as long = &H0&

'   Field AUX_3_CTL                                                         
'    On/off control bits for Auxiliary 3 output                               
public const SMC_FPGA_AUX_3_CTL__ADDR as long= &hB207&
public const SMC_FPGA_AUX_3_CTL__MASK as long= &h3&
public const SMC_FPGA_AUX_3_CTL__SHIFT as long= &h0&
public const SMC_FPGA_AUX_3_CTL_ON as long = &H1&
public const SMC_FPGA_AUX_3_CTL_OFF as long = &H0&
public const SMC_FPGA_AUX_3_CTL_LOW as long = &H3&

'   Field AUX_2_CTL                                                         
'    On/off control bits for Auxiliary 2 output                               
public const SMC_FPGA_AUX_2_CTL__ADDR as long= &hB206&
public const SMC_FPGA_AUX_2_CTL__MASK as long= &h3&
public const SMC_FPGA_AUX_2_CTL__SHIFT as long= &h0&
public const SMC_FPGA_AUX_2_CTL_ON as long = &H1&
public const SMC_FPGA_AUX_2_CTL_OFF as long = &H0&
public const SMC_FPGA_AUX_2_CTL_LOW as long = &H3&

'   Field AUX_1_CTL                                                         
'    On/off control bits for Auxiliary 1 output                               
public const SMC_FPGA_AUX_1_CTL__ADDR as long= &hB205&
public const SMC_FPGA_AUX_1_CTL__MASK as long= &h3&
public const SMC_FPGA_AUX_1_CTL__SHIFT as long= &h0&
public const SMC_FPGA_AUX_1_CTL_ON as long = &H1&
public const SMC_FPGA_AUX_1_CTL_OFF as long = &H0&
public const SMC_FPGA_AUX_1_CTL_LOW as long = &H3&

'   Field AUX_0_CTL                                                         
'    On/off control bits for Auxiliary 0 output                               
public const SMC_FPGA_AUX_0_CTL__ADDR as long= &hB204&
public const SMC_FPGA_AUX_0_CTL__MASK as long= &h3&
public const SMC_FPGA_AUX_0_CTL__SHIFT as long= &h0&
public const SMC_FPGA_AUX_0_CTL_ON as long = &H1&
public const SMC_FPGA_AUX_0_CTL_OFF as long = &H0&
public const SMC_FPGA_AUX_0_CTL_LOW as long = &H3&

'   Field AUX_FAN_CTL                                                       
'    On/off control bits for Auxiliary fan output                             
public const SMC_FPGA_AUX_FAN_CTL__ADDR as long= &hB203&
public const SMC_FPGA_AUX_FAN_CTL__MASK as long= &h3&
public const SMC_FPGA_AUX_FAN_CTL__SHIFT as long= &h0&
public const SMC_FPGA_AUX_FAN_CTL_ON as long = &H1&
public const SMC_FPGA_AUX_FAN_CTL_OFF as long = &H0&
public const SMC_FPGA_AUX_FAN_CTL_LOW as long = &H3&

'   Field K1_ENABLE                                                         
'    Enable for On/off control bit for K1                                     
public const SMC_FPGA_K1_ENABLE__ADDR as long= &hB20D&
public const SMC_FPGA_K1_ENABLE__MASK as long= &h1&
public const SMC_FPGA_K1_ENABLE__SHIFT as long= &h0&
public const SMC_FPGA_K1_ENABLE_ENABLE as long = &H1&
public const SMC_FPGA_K1_ENABLE_DISABLE as long = &H0&

'   Field K1_ON                                                             
'    On/off control bit for K1                                                
public const SMC_FPGA_K1_ON__ADDR as long= &hB202&
public const SMC_FPGA_K1_ON__MASK as long= &h1&
public const SMC_FPGA_K1_ON__SHIFT as long= &h0&
public const SMC_FPGA_K1_ON_ON as long = &H1&
public const SMC_FPGA_K1_ON_OFF as long = &H0&

'   Field V48_ENABLE                                                        
'    Enable for On/off control bit for 48V                                    
public const SMC_FPGA_V48_ENABLE__ADDR as long= &hB20C&
public const SMC_FPGA_V48_ENABLE__MASK as long= &h1&
public const SMC_FPGA_V48_ENABLE__SHIFT as long= &h0&
public const SMC_FPGA_V48_ENABLE_ENABLE as long = &H1&
public const SMC_FPGA_V48_ENABLE_DISABLE as long = &H0&

'   Field V48_ON                                                            
'    On/off control bit for 48V                                               
public const SMC_FPGA_V48_ON__ADDR as long= &hB201&
public const SMC_FPGA_V48_ON__MASK as long= &h1&
public const SMC_FPGA_V48_ON__SHIFT as long= &h0&
public const SMC_FPGA_V48_ON_ON as long = &H1&
public const SMC_FPGA_V48_ON_OFF as long = &H0&
Public Declare Function SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_cntrl_jag_48vdc_on_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_cntrl_jag_switched_ac_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_smc_cntrl_bc_switched_ac_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_B_CNTRL_BC_48VDC_DC90_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_cntrl_bc_48vdc_dc90_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_B_DC90_48V_ENABLE_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_dc90_48v_enable_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_B_CNTRL_BC_48VDC_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_cntrl_bc_48vdc_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_BC_TACH1_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach1_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_BC_TACH0_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach0_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_GEN_FREQ_CTR_MUX_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_gen_freq_ctr_mux_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_CTR_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_ctr_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_CLR_LOCK_OUT_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_lock_out_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_CLR_MAINT_REG_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_maint_reg_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_CLR_REGS_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_regs_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_CLR_CTRS_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_ctrs_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_AUX_3_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_3_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_AUX_2_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_2_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_AUX_1_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_1_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_AUX_0_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_0_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_AUX_FAN_CTL_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_fan_ctl_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_K1_ENABLE_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_k1_enable_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_K1_ON_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_k1_on_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_V48_ENABLE_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v48_enable_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_V48_ON_W Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v48_on_w@4"                     (ByVal data As Long) as long
Public Declare Function SMC_FPGA_SMC_MON_PDU_JAG_THERMAL_FAULT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_pdu_jag_thermal_fault_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_PDU_JAG_48V_LVL_ON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_pdu_jag_48v_lvl_on_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_PDU_JAG_48V_GOOD_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_pdu_jag_48v_good_r@0" As Long
Public Declare Function SMC_FPGA_SMC_CNTRL_JAG_48VDC_ON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_cntrl_jag_48vdc_on_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_PDU_K1_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_pdu_k1_r@0" As Long
Public Declare Function SMC_FPGA_SMC_CNTRL_JAG_SWITCHED_AC_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_cntrl_jag_switched_ac_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_AC_ON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_ac_on_r@0" As Long
Public Declare Function SMC_FPGA_B_SMC_CNTRL_BC_SWITCHED_AC_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_smc_cntrl_bc_switched_ac_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_FAN1_STATE_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_fan1_state_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_FAN0_STATE_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_fan0_state_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_PHASE_LOSS_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_phase_loss_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_OVR_TMP_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_ovr_tmp_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_AC_PWR_FAULT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_ac_pwr_fault_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_BC_OUTPUT_FAULT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_bc_output_fault_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_DC90_48V_ON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_dc90_48v_on_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_DC90_OVR_TMP_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_dc90_ovr_tmp_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_DC90_AC_PWR_FAULT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_dc90_ac_pwr_fault_r@0" As Long
Public Declare Function SMC_FPGA_SMC_MON_DC90_OUTPUT_FAULT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_smc_mon_dc90_output_fault_r@0" As Long
Public Declare Function SMC_FPGA_B_CNTRL_BC_48VDC_DC90_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_cntrl_bc_48vdc_dc90_r@0" As Long
Public Declare Function SMC_FPGA_B_DC90_48V_ENABLE_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_dc90_48v_enable_r@0" As Long
Public Declare Function SMC_FPGA_B_CNTRL_BC_48VDC_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_b_cntrl_bc_48vdc_r@0" As Long
Public Declare Function SMC_FPGA_BC_TACH1_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach1_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_BC_TACH0_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach0_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_GEN_FREQ_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_gen_freq_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_MAIN_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_main_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_I2_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_i2_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_I1_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_i1_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_V0_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v0_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_MAINT_MON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_maint_mon_r@0" As Long
Public Declare Function SMC_FPGA_ID_REV_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_id_rev_r@0" As Long
Public Declare Function SMC_FPGA_BC_TACH1_CTR_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach1_ctr_hi_r@0" As Long
Public Declare Function SMC_FPGA_BC_TACH1_CTR_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach1_ctr_lo_r@0" As Long
Public Declare Function SMC_FPGA_BC_TACH0_CTR_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach0_ctr_hi_r@0" As Long
Public Declare Function SMC_FPGA_BC_TACH0_CTR_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_bc_tach0_ctr_lo_r@0" As Long
Public Declare Function SMC_FPGA_GEN_FREQ_CTR_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_gen_freq_ctr_hi_r@0" As Long
Public Declare Function SMC_FPGA_GEN_FREQ_CTR_MID_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_gen_freq_ctr_mid_r@0" As Long
Public Declare Function SMC_FPGA_GEN_FREQ_CTR_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_gen_freq_ctr_lo_r@0" As Long
Public Declare Function SMC_FPGA_MAIN_BLOWER_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_main_blower_hi_r@0" As Long
Public Declare Function SMC_FPGA_MAIN_BLOWER_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_main_blower_lo_r@0" As Long
Public Declare Function SMC_FPGA_I2_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_i2_hi_r@0" As Long
Public Declare Function SMC_FPGA_I2_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_i2_lo_r@0" As Long
Public Declare Function SMC_FPGA_I1_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_i1_hi_r@0" As Long
Public Declare Function SMC_FPGA_I1_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_i1_lo_r@0" As Long
Public Declare Function SMC_FPGA_V0_HI_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v0_hi_r@0" As Long
Public Declare Function SMC_FPGA_V0_LO_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v0_lo_r@0" As Long
Public Declare Function SMC_FPGA_GEN_FREQ_CTR_MUX_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_gen_freq_ctr_mux_r@0" As Long
Public Declare Function SMC_FPGA_CTR_CTL_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_ctr_ctl_r@0" As Long
Public Declare Function SMC_FPGA_CLR_LOCK_OUT_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_lock_out_r@0" As Long
Public Declare Function SMC_FPGA_CLR_MAINT_REG_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_maint_reg_r@0" As Long
Public Declare Function SMC_FPGA_CLR_REGS_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_regs_r@0" As Long
Public Declare Function SMC_FPGA_CLR_CTRS_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_clr_ctrs_r@0" As Long
Public Declare Function SMC_FPGA_AUX_3_CTL_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_3_ctl_r@0" As Long
Public Declare Function SMC_FPGA_AUX_2_CTL_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_2_ctl_r@0" As Long
Public Declare Function SMC_FPGA_AUX_1_CTL_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_1_ctl_r@0" As Long
Public Declare Function SMC_FPGA_AUX_0_CTL_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_0_ctl_r@0" As Long
Public Declare Function SMC_FPGA_AUX_FAN_CTL_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_aux_fan_ctl_r@0" As Long
Public Declare Function SMC_FPGA_K1_ENABLE_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_k1_enable_r@0" As Long
Public Declare Function SMC_FPGA_K1_ON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_k1_on_r@0" As Long
Public Declare Function SMC_FPGA_V48_ENABLE_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v48_enable_r@0" As Long
Public Declare Function SMC_FPGA_V48_ON_R Lib "smc_fpga_idl.dll" Alias "_smc_fpga_v48_on_r@0" As Long
