'' ****************************************************************************

''  Visual Basic HEADER FILE FOR INSTRUMENT SMC_FPGA

''   PREPARED BY IDL VERSION 2.30e 

''   DO NOT EDIT THIS FILE-YOU'LL LOSE THE ABILITY TO RERUN IDL

'' ****************************************************************************

